### PR TITLE
fix(StatusIcon): fixed icon size in StatusIcon component

### LINKED ISSUE #15682: Custom icons are smaller vs native container icons
### Bug description

Image

See above, whenever you put a custom icon, it is a different size vs the other native icons part of podman desktop.

### Operating system

mac m1

### Installation Method

None

### Version

1.24.0

### Steps to reproduce

1. Create a few containers.
2. Start Kind cluster (has a custom icon)
3. See the size difference

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Fixes StatusIcon size and centering

### Screenshot / video of UI
Prev:
Image

Now: 
image

### What issues does this PR fix or reference?
Closes: #15682 

### How to test this PR?
Open Container table and see the status icons
Check other places in UI if there is nothing broken 

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
Centering fixed. 👍🏼 Icons provided via woff contribution are marginally bigger, but still don't fill the space like the built-in SVGs:

Screenshot 2026-01-22 at 9 47 41 AM

Can you try with ai lab or bootc images?

**Comment by gastoner** [comment]
@deboer-tim I've updated the sizes of custom icons, but e.g. kind image is slightly bigger than bootc image, so I had to hardcode the size of the StatusIcon to be unified. 

Quite tricky this one with different sizes of icons, might be worth updating the custom wolf icons to same size? 
With latest changes:

Screenshot 2026-01-22 at 18 08 01

Screenshot 2026-01-22 at 18 08 33

**Comment by deboer-tim** [comment]
Bootc looks better, but I'm hesitant to approve the change given it's a bit hard-coded and the kind icon touches the icon border for me now. Maybe we go back to the first commit and take the win on alignment and work on size separately?

FWIW, I tried several online woff2 font viewers and none could display both the kind and bootc fonts. 😕 From what I did see the bootc icon looked roughly proportional to (e.g.) a large/capital letter, but the kind icon looked extra wide. We might need to see if there is a convention or correct size for woff2 characters and confirm our fonts conform before we try to tackle size in the icon.

**Comment by gastoner** [comment]
> Bootc looks better, but I'm hesitant to approve the change given it's a bit hard-coded and the kind icon touches the icon border for me now. Maybe we go back to the first commit and take the win on alignment and work on size separately?
> 
> FWIW, I tried several online woff2 font viewers and none could display both the kind and bootc fonts. 😕 From what I did see the bootc icon looked roughly proportional to (e.g.) a large/capital letter, but the kind icon looked extra wide. We might need to see if there is a convention or correct size for woff2 characters and confirm our fonts conform before we try to tackle size in the icon.

The size should be also updated with the first commit, if you try to update the StatusIcon with removed `text-xs` the custom icons will be smaller. Now it should use `text-md` by default, I guess

**Comment by gastoner** [comment]
@deboer-tim removed the second commit

File: packages/ui/src/lib/icons/Icon.svelte [hunk 1]
```diff
@@ -27,12 +27,12 @@ const IconComponent = icon;
     <!-- fas fa- and far fa- and fab fa- for Font awesome icons -->
     <!-- -icon for extension icons e.g. 'kind-icon' -->
     {#if icon.startsWith('fas fa-') || icon.startsWith('far fa-') || icon.startsWith('fab fa-') || icon.endsWith('-icon')}
-        <span class={`${icon} ${size} ${className}`} {role} {title}></span>
+        <span class={`${icon} ${size} ${className} flex flex-row`} {role} {title}></span>
```
Comment (deboer-tim) [inline packages/ui/src/lib/icons/Icon.svelte]: I was trying to understand what each line in the change was doing and noticed something odd. With only the change to StatusIcon the inner icon gets bigger 👍🏼 but is still slightly mis-aligned:

Image

When adding this line the icon becomes aligned - but it does it by shrinking the outer box slightly compared to the normal size:

Image

I only noticed this because I was toggling the change on and off, and it's minor, but I don't think we want to affect the size of the status icon. I think we either take just the size fix and defer alignment, or need to find a different way to fix the alignment.

Comment (gastoner) [reply packages/ui/src/lib/icons/Icon.svelte]: +1 I think we can pixel-perfect this icon since it should be only Icon component used :thinking:

**Review by deboer-tim — APPROVED** [review]
Thanks for updating, and good to fix this issue which has been around for a while!

Would be good to update the test as well with a `expect(icon).not.toHaveAttribute('text-xs');`

**Comment by gastoner** [comment]
@deboer-tim added
