### PR TITLE
fix(kubectl-cli): sync provider version on CLI tool install/uninstall

### LINKED ISSUE #17091: Resources page shows previously uninstalled kubectl version
### Bug description

Same as #17063 but for kubectl. After updating kubectl via CLI Tools or Resources page, then uninstalling it, the Resources page still shows the stale version until restart.

`doUninstall` does not call `provider.updateVersion()` to clear the version. `doInstall` also doesn't set it (only `doUpdate` does).

### Operating system

All

### Version

1.26.0

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

Syncs the kubectl provider version (shown on Resources page) with CLI tool install/uninstall actions.

Two fixes:
- `doUninstall`: clears provider version so Resources page no longer shows a stale version after uninstall
- `doInstall`: sets provider version so Resources page shows the version immediately after install (consistent with `doUpdate` which already did this)

### Screenshot / video of UI

https://github.com/user-attachments/assets/8ba158e1-2728-480d-bbd6-04780419ed11

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/17091

### How to test this PR?

1. Install kubectl from CLI Tools page → Resources page should now show the version
2. Uninstall kubectl from CLI Tools page → Resources page should no longer show any version

- [x] Tests are covering the bug fix or the new feature

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

File: extensions/kubectl-cli/src/extension.ts [hunk 1]
```diff
@@ -448,6 +449,7 @@ async function postActivate(
 
       // update the version to undefined
       vpState.version = undefined;
+      provider.updateVersion('');
```
Comment (cdrage) [inline extensions/kubectl-cli/src/extension.ts:452]: small nit, I see test is covering this, I still find it odd that it's '', but 🤷 

implementation works, so LGTM

**Review by cdrage — APPROVED** [review]
LGTM
