### PR TITLE
fix: add bottom spacing to resources page

### LINKED ISSUE #15466: Resources provider cards go to the edge on the bottom of the screen
### Bug description

Image

Same as https://github.com/podman-desktop/podman-desktop/issues/15395

There should be a little bit of spacing on the bottom so you can read the Resources provider well :) 

### Operating system

mac m1

### Installation Method

None

### Version

1.24.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shri3016**
### What does this PR do?
Fixes the spacing issue on the Resources page, allowing the content to size naturally and preventing the bottom content from being cut off.

### Screenshot / video of UI

Screenshot of UI with space

### What issues does this PR fix or reference?

This helps to fix #15466 

### How to test this PR?

1. Go to Settings > Resources.
2. Scroll down to the bottom of the page .
3. Verify that the Resources provider content at the bottom has proper spacing and is not squished against the edge.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by shri3016** [comment]
Hi @benoitf @gastoner @bmahabirbu !
This is my first PR to Podman Desktop which fixes #15466 
Can you or anyone from your team please review this and let me know if there's anything else needed from my side or if any changes are required. Thanks!

**Comment by gastoner** [comment]
Hello @shri3016 thank you for the contribution!
Usually you need 2 approval to merge the PR + the required checks need to pass :heavy_check_mark: (I've approved the workflow run)
But for this PR is should be fine :D 

Also not sure if you have already read the 
https://github.com/podman-desktop/podman-desktop/blob/main/CODE-GUIDELINES.md
and https://github.com/podman-desktop/podman-desktop/blob/main/CONTRIBUTING.md

**Comment by shri3016** [comment]
> Hello @shri3016 thank you for the contribution! Usually you need 2 approval to merge the PR + the required checks need to pass ✔️ (I've approved the workflow run) But for this PR is should be fine :D
> 
> Also not sure if you have already read the https://github.com/podman-desktop/podman-desktop/blob/main/CODE-GUIDELINES.md and https://github.com/podman-desktop/podman-desktop/blob/main/CONTRIBUTING.md

Hi @gastoner,Thank you for the review!
I've read the code-guidelines and the contributing-guidelines. Can you please let me know if there’s anything I’m missing or should add to this PR. Thanks again for your guidance :)

File: packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte [hunk 1]
```diff
@@ -436,7 +436,7 @@ $effect(() => {
         class="text-[var(--pd-content-text)] underline underline-offset-2">Extensions</a>
     </span>
   {/snippet}
-  <div class="h-full" role="region" aria-label="Featured Provider Resources">
+  <div class="pb-0.5" role="region" aria-label="Featured Provider Resources">
```
Comment (gastoner) [inline packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte]: I've tried this and I've found that the resources cards does have the bottom margin, but since there was `h-full` it stripping it down to 0 

On linux I can see this: there is a tiny white line under the last resource (the `pb-0.5`)
Image

And here I've removed the whole `class` completely: 
Image

So I think we can just remove whole `class` 
Can you try this on your machine?

Comment (shri3016) [reply packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte]: Hi @gastoner,Thanks for testing this. You are absolutely right! I have removed the class entirely now (Attaching the screenshot below).
screenshot of spacing
The spacing looks correct now without the white line.Please take another look when you have time and let me know if any changes are required from my side.Thanks again for the guidance:)

**Review by benoitf — APPROVED** [review]
