### PR TITLE
fix(electron-builder): bundle extensions-extra in extraResources

### LINKED ISSUE #15416: Test RHEL extension when bundled into the product
### Bug description

Seems issues are spawned when VMs are created.

### Operating system

Windows

### Installation Method

None

### Version

1.24.0

### Steps to reproduce

- Generate bundle with the RHEL extension bundled
- Test extension

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

The first implementation were adding the `extensions-extra in the `files`  property of electron builder, copying the content inside  the `app.asar` which seems to have some issues (See https://github.com/podman-desktop/podman-desktop/issues/15416#issuecomment-3714904956 for full details).

The solution provided in this PR is to move the `extensions-extra` folder into the `extraResources` which would make it appear next to the app.asar.

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/15416

### How to test this PR?

**Testing manually**

⚠️ **The problem has been reported on Windows, the following steps will not work on non-windows as macadam need to be downloaded manually.**

1. Checkout this branch
2. Add the following extensions inside the `product.json`
```json
  [...]
  "extensions": {
    "remote": [{
      "name": "podman-desktop-extension-layers-explorer",
      "oci": "ghcr.io/podman-desktop/podman-desktop-extension-layers-explorer:dfb3d8ef35b852c758c8c7eba24db581f694a3fb"
    }, {
      "name": "podman-desktop-rhel-ext",
      "oci": "ghcr.io/redhat-developer/podman-desktop-rhel-ext:99acb52aad14d0a1fa7276805568a30f6987d1d9"
    }, {
      "name": "podman-desktop-redhat-account-ext",
      "oci": "ghcr.io/redhat-developer/podman-desktop-redhat-account-ext@sha256:9e7bbd86536ad9eef80d8e3168adc6ee01f3b6ae29e65c903d1e87449495e5ff"
    }]
  }
```
3. Run `pnpm compile:current`
4. Open the explorer and got inside the `dist` folder
5. Start `podman-desktop-1.25.0-next.exe`
6. Assert all bundled extensions are activated successfully
7. Create a new VM
image

8. Assert the VM is running as expected 🚀 
image

### CODE REVIEW

File: packages/main/src/plugin/extension/extension-loader.ts [hunk 1]
```diff
@@ -458,7 +458,7 @@ export class ExtensionLoader implements IAsyncDisposable {
       // in production mode, use the extensions & extensions-extra locally
       const promises = await Promise.all([
         this.readProductionFolders(path.join(__dirname, '../../../extensions')),
```
Comment (gastoner) [inline packages/main/src/plugin/extension/extension-loader.ts:460]: Might be worth change the path to `extensions` in separate issue too ?

**Review by gastoner — COMMENTED** [review]
Codewise LGTM, just cant verify :(

**Review by benoitf — COMMENTED** [review]
it's not working on my end, the root problem is on the installation of macadam binaries, not on creating a VM. So the test case is to check if macadam binaries are installed.

on my end, before starting the app

1. I'm removing `/opt/macadam` folder

2. add rhel extension in product.json
```
 "extensions": {
    "remote": [
 {
      "name": "podman-desktop-rhel-ext",
      "oci": "ghcr.io/redhat-developer/podman-desktop-rhel-ext:99acb52aad14d0a1fa7276805568a30f6987d1d9"
    }]
  }
```

3. build the app folder using `pnpm compile:current --mac dir --arm64`

4. self signing the binary  `codesign --force --deep --sign - ./dist/mac-arm64/Podman\ Desktop.app`

5. launch Podman Desktop using `./dist/mac-arm64/Podman\ Desktop.app/Contents/MacOS/Podman\ Desktop` 
I can see a osascript prompt (rhel extension asking me to install macadam binaries), I enter my password but then it fails

in the logs I see: 

`Activating extension redhat.rhel-vms failed error:Command execution failed with exit code 1: Command execution failed with exit code 1`

6. I'm also trying, disabling/enabling back rhel extension but it's still failing

7. If I go to the extensions tab and manually install the same OCI image `ghcr.io/redhat-developer/podman-desktop-rhel-ext:99acb52aad14d0a1fa7276805568a30f6987d1d9` I see the prompt and on this path it works.

**Review by benoitf — APPROVED** [review]
problem is on admin/command and spaces

**Comment by feloy** [comment]
> problem is on admin/command and spaces

-> problem reported in issue https://github.com/podman-desktop/podman-desktop/issues/15582

**Review by jeffmaury — APPROVED** [review]
Tested on Windows and could create a RHEL VM

**Comment by cbr7** [comment]
@axel7083 I tried to build it locally to test this branch but I'm getting the following error:

image

This as after adding the files to the product.json file as you mention in step 2.

**Comment by cbr7** [comment]
Checked this on macos, working fine now.

**Review by cbr7 — APPROVED** [review]

**Comment by benoitf** [comment]
this PR + https://github.com/podman-desktop/podman-desktop/pull/15583 together are fixing the issue on my end

**Comment by feloy** [comment]
Works for me on Mac, only with #15583 applied

Without #15583, the problem is that osascript is executed with these args, and the `-pkg` path contains unescaped space (`...Podman Desktop.app...`)
```
  '-e',
  'do shell script "installer -pkg /Users/phmartin/Documents/gits/podman-desktop/dist/mac-arm64/Podman Desktop.app/Contents/Resources/extensions-extra/podman-desktop-rhel-ext/dist/node_modules/@crc-org/macadam.js/binaries/macadam-installer-macos-universal.pkg -target /" with prompt "Podman Desktop requires admin privileges " with administrator privileges'
```

**Comment by feloy** [comment]
Also tested with the upcoming version of RHEL extension (PR https://github.com/redhat-developer/podman-desktop-rhel-ext/pull/409, OCI image quay.io/phmartin/rhel:15), and it works as expected

**Review by feloy — APPROVED** [review]
LGTM with #15583

**Comment by ScrewTSW** [comment]
@odockal @axel7083 

re-tested again on a fresh Windows set-up
updated extensions to latest digests:
```
"extensions": {
    "remote": [{
      "name": "podman-desktop-extension-layers-explorer",
      "oci": "ghcr.io/podman-desktop/podman-desktop-extension-layers-explorer:8a55e05edcf556598cda0babc39288a338d84c99"
    }, {
      "name": "podman-desktop-rhel-ext",
      "oci": "ghcr.io/redhat-developer/podman-desktop-rhel-ext:67466238ed2fa54225272dd9ff50a1b4a403c7e2"
    }, {
      "name": "podman-desktop-redhat-account-ext",
      "oci": "ghcr.io/redhat-developer/podman-desktop-redhat-account-ext@sha256:12ff6930161546ece585bce5418cdaa5882c8b69794a1a6b983a2a791e955c8e"
    }]
  }
```
Layers explorer works
Red Hat SSO works
Rhel VM failed to start a machine
image
Machine details:
image
I SSO authenticated before attempting to create a Rhel VM
