### PR TITLE
fix(renderer): open SearchBar on F1 key only

### LINKED ISSUE #15219: SearchBar should not react to keyboard inputs unless it is open
### Bug description

In curent verison of PD when you type e.g.  ">" the SearchBar will open 

The searchbar should react to keyboard shortcuts only when opened 
see https://github.com/podman-desktop/podman-desktop/issues/15033#issuecomment-3602966133

### Operating system

All

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JustMell0**
Signed-off-by: Dias Tursynbayev <original.justmello1337@gmail.com>

### What does this PR do?

This PR edits the behavior of Search Bar to open only if F1 key pressed

### What issues does this PR fix or reference?

Closes #15219

### How to test this PR?

1. Press any Search Bar shortcut key other than F1 – the Search Bar should not open.
2. Press F1 – the Search Bar should open.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/dialogs/CommandPalette.svelte [hunk 1]
```diff
@@ -168,8 +168,13 @@ function displaySearchBar(): void {
...
 
 async function handleKeydown(e: KeyboardEvent): Promise<void> {
+  // open palette only if F1 key is pressed when pallet is not already visible
+  if (!display && e.key !== `${F1}`) {
+    return;
+  }
+
   // toggle display using F1 or ESC keys
-  if (e.key === `${F1}` || e.key === '>') {
+  if (e.key === `${F1}` || e.key === `>`) {
```
Comment (benoitf) [inline packages/renderer/src/lib/dialogs/CommandPalette.svelte]: question: why replace
```
 '>'
```

 by
```
 `>`
```

?

File: packages/renderer/src/lib/dialogs/CommandPalette.svelte [hunk 2]
```diff
@@ -168,8 +168,13 @@ function displaySearchBar(): void {
 }
 
 async function handleKeydown(e: KeyboardEvent): Promise<void> {
+  // open palette only if F1 key is pressed when pallet is not already visible
```
Comment (benoitf) [inline packages/renderer/src/lib/dialogs/CommandPalette.svelte]: typo: it's palette

Comment (JustMell0) [reply packages/renderer/src/lib/dialogs/CommandPalette.svelte]: Thanks for the review! Fixed in the latest commit

File: packages/renderer/src/lib/dialogs/CommandPalette.svelte [hunk 3]
```diff
@@ -168,6 +168,11 @@ function displaySearchBar(): void {
 }
 
 async function handleKeydown(e: KeyboardEvent): Promise<void> {
+  // open palette only if F1 key is pressed when palette is not already visible
+  if (!display && e.key !== `${F1}`) {
+    return;
+  }
+
   // toggle display using F1 or ESC keys
   if (e.key === `${F1}` || e.key === '>') {
```
Comment (axel7083) [inline packages/renderer/src/lib/dialogs/CommandPalette.svelte:177]: question: we seems to already have a condition here checking for F1 click, what is adding the check above?

Comment (gastoner) [reply packages/renderer/src/lib/dialogs/CommandPalette.svelte:177]: Rn we react to every shortcut by opening the command pallete in given tab asociaed with the shortcut

Now we want to react only to F1 shortcut to open the palette, so if is the palette not visible, react only to F1 shortcut, ignore otherwise

**Review by benoitf — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]
