### PR TITLE
fix: env. var. CI should be tested when in lowercase due to powershel…

### LINKED ISSUE #15065: playwright test exported constant isCI is not evaluated at runtime
### Bug description

Right now this constant in `tests/playwright/src/utility/platform.ts`
```
export const isCI = process.env.CI ? process.env.CI === 'true' : false;
```
seems to be defined at the build time, not at runtime.
We need to rewrite it into a function is it can evaluate env. var during runtime,.

### Operating system

any

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by odockal**
…l literal value for $true

### What does this PR do?
Powershell value for `$true` is `True`, thus isCI fails to evaluate properly when run from powershell.

### What issues does this PR fix or reference?
#15065 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by cbr7 — APPROVED** [review]

File: tests/playwright/src/utility/platform.ts [hunk 1]
```diff
@@ -23,4 +23,5 @@ export const isMac = os.platform() === 'darwin';
 export const isWindows = os.platform() === 'win32';
 export const archType = os.arch();
 
-export const isCI = process.env.CI ? process.env.CI === 'true' : false;
+// powershell $true value is 'True', we need to make it a lowercase first
+export const isCI = process.env.CI ? process.env.CI.toLowerCase() === 'true' : false;
```
Comment (benoitf) [inline tests/playwright/src/utility/platform.ts]:
```suggestion
export const isCI = String(process.env.CI).toLowerCase() === 'true';
```

**Review by benoitf — APPROVED** [review]
