### PR TITLE
fix: verify the ports requested for kind cluster are free

### LINKED ISSUE #12405: When creating a kind cluster with default values, http port for kind control plane should be detected dynamically
### Bug description

On RHEL for example, I am trying to create a kind cluster with default parameters: http port: 9090, https: 9443. But by default, rhel has 9090 port number dedicated to a RHEL web console. We should detect that prior to setting a default port number for Kind cluster create page.

### Operating system

Linux, Rhel

### Installation Method

None

### Version

1.18.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

PR checks if ports requested for kind cluster is free and show auditor error message.

### Screenshot / video of UI

https://github.com/user-attachments/assets/b65bf794-cb98-4ce8-8e46-317f47c5c5f2

### What issues does this PR fix or reference?

Fix #12405.

### How to test this PR?

Create two kind clusters. Creating second cluster should trigger request to use different free ports.

- [x] Tests are covering the bug fix or the new feature (TBD)

### CODE REVIEW

File: extensions/kind/src/create-cluster.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ import { parseAllDocuments, stringify } from 'yaml';
 
 import ingressManifests from '/@/resources/contour.yaml?raw';
 
+import { getFreePort } from '../../../packages/main/src/plugin/util/port';
```
Comment (dgolovin) [inline extensions/kind/src/create-cluster.ts]: @benoitf is there a better way to reuse port.ts? Should I use available npm package instead?

Comment (simonrey1) [reply extensions/kind/src/create-cluster.ts]: Maybe you could add it using a separate PR to `packages/main/src/plugin/extension/extension-loader.ts`, and the use the `extensionApi` to call it?

**Review by jeffmaury — COMMENTED** [review]
Can't we use the diagnostic feature to report port that are already in use ?

**Comment by dgolovin** [comment]
> Can't we use the diagnostic feature to report port that are already in use ?

@jeffmaury do you mean do it throug autditItems callback, then let user to update it manulay?

**Comment by jeffmaury** [comment]
Yes

File: extensions/kind/src/create-cluster.ts (hunk 1 above)
Comment (dgolovin) [reply extensions/kind/src/create-cluster.ts]: I am not sure it should be part of extensionApi. I'd rather use relative path or external package. I'll stick to relative path for now.

**Comment by dgolovin** [comment]
@jeffmaury @eqqe  I updated screen-cast. Please review.

**Comment by jiridostal** [comment]
1. Should we disable the Create button when the user runs into the occupied port and the error is shown on top?
2. The final error message has a different design, but this should be another PR as it's not related to this issue.

**Comment by dgolovin** [comment]
> 1. Should we disable the Create button when the user runs into the occupied port and the error is shown on top?

@jiridostal The audit error does block creating kind instance, it just does not visible in screen recording

image

**Comment by dgolovin** [comment]
> 2\. The final error message has a different design, but this should be another PR as it's not related to this issue.

yes, audit and instance creation errors look differently. I'll open issue for that.

**Review by feloy — CHANGES_REQUESTED** [review]
I don't think that using freePort from main works. Having it shared with extension-api looks a good idea to me, as this code is already duplicated in other extensions

**Review by gastoner — APPROVED** [review]
Works fine on Linux

**Review by cdrage — APPROVED** [review]
I ran into zero issues when testing this out, implementation wise LGTM.

When using `getFreePort` it worked correctly.

I believe `getFreePort` was fixed recently by @bmahabirbu here: https://github.com/podman-desktop/podman-desktop/pull/13481 regarding the free ports for localhost + 0.0.0.0

LGTM my side.

**Comment by dgolovin** [comment]
@feloy I added new PR to introduce new net module with port detection related functions see #13625.

File: extensions/kind/src/create-cluster.ts (hunk 1 above)
Comment (dgolovin) [reply extensions/kind/src/create-cluster.ts]: @eqqe added new net module with getFreePort function (see #13625).

**Review by feloy — APPROVED** [review]
