### PR TITLE
fix: added different key to containers when no id is found

### LINKED ISSUE #13048: Pod may be listed several times on the pod page
### Bug description

When creating a Kind cluster I wanted to monitor the pod and it seems a pod maybe listed several times (based on state ?)

Image

Also I have errors in logs:

```
VM5:62 main ↪️ event is {status: 'create', Type: 'volume', Action: 'create', Actor: {…}, scope: 'local', …}
VM5:62 main ↪️ event is {status: 'pull', id: 'd6b20550c77b11385dd30115ba29dbf9a9bfc98c2f28ff7d162a6ad7c9686251', Type: 'image', Action: 'pull', Actor: {…}, …}
VM5:62 main ↪️ event is {status: 'create', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'create', …}
VM5:62 main ↪️ event is {status: 'init', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'init', …}
VM5:62 main ↪️ event is {status: 'start', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'start', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
VM5:62 main ↪️ event is {status: 'exec', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec', …}
VM5:62 main ↪️ event is {status: 'exec_died', id: 'c28e32e12038321853db0f4652235cbcc4e119246dd0484350e9db58340598db', from: 'docker.io/kindest/node@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f', Type: 'container', Action: 'exec_died', …}
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467
chunk-V75KQ2P3.js?v=f7139a43:182 Uncaught Svelte error: each_key_duplicate
Keyed each block has duplicate key at indexes 0 and 1
https://svelte.dev/e/each_key_duplicate

	in <unknown>
	in Dots.svelte
	in PodColumnContainers.svelte
	in Table.svelte
	in NavPage.svelte
	in KubernetesObjectsList.svelte
	in PodsList.svelte
	in Route.svelte
	in Route.svelte
	in App.svelte
	in Loader.svelte

    at each_key_duplicate (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:182:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3698:9
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
    at update_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1810:21)
    at create_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2206:7)
    at render_effect (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:2335:10)
    at Module.validate_each_keys (http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:3686:3)
    at http://localhost:5173/src/lib/ui/Dots.svelte:144:8
    at http://localhost:5173/node_modules/.vite/deps/chunk-ANGXYLDB.js?v=f7139a43:1015:27
    at update_reaction (http://localhost:5173/node_modules/.vite/deps/chunk-V75KQ2P3.js?v=f7139a43:1690:23)
each_key_duplicate @ chunk-V75KQ2P3.js?v=f7139a43:182
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:3698
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
render_effect @ chunk-V75KQ2P3.js?v=f7139a43:2335
validate_each_keys @ chunk-ANGXYLDB.js?v=f7139a43:3686
(anonymous) @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
alternate @ Dots.svelte:21
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:623
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:623
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Dots.svelte:14
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
Dots @ Dots.svelte:23
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
PodColumnContainers @ PodColumnContainers.svelte:2
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:320
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:314
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
wrapper @ chunk-ANGXYLDB.js?v=f7139a43:307
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1292
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
component @ chunk-ANGXYLDB.js?v=f7139a43:1285
consequent_4 @ Table.svelte:287
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:612
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
update_branch @ chunk-ANGXYLDB.js?v=f7139a43:612
set_branch @ chunk-ANGXYLDB.js?v=f7139a43:580
(anonymous) @ Table.svelte:284
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:637
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
if_block @ chunk-ANGXYLDB.js?v=f7139a43:635
(anonymous) @ Table.svelte:286
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
block @ chunk-V75KQ2P3.js?v=f7139a43:2355
each @ chunk-ANGXYLDB.js?v=f7139a43:753
(anonymous) @ Table.svelte:264
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1015
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
create_effect @ chunk-V75KQ2P3.js?v=f7139a43:2206
branch @ chunk-V75KQ2P3.js?v=f7139a43:2358
create_item @ chunk-ANGXYLDB.js?v=f7139a43:1015
reconcile @ chunk-ANGXYLDB.js?v=f7139a43:865
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:804
update_reaction @ chunk-V75KQ2P3.js?v=f7139a43:1690
update_effect @ chunk-V75KQ2P3.js?v=f7139a43:1810
process_effects @ chunk-V75KQ2P3.js?v=f7139a43:1943
flush_queued_root_effects @ chunk-V75KQ2P3.js?v=f7139a43:1880
chunk-ANGXYLDB.js?v=f7139a43:1404 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at Array.<anonymous> (chunk-ANGXYLDB.js?v=f7139a43:1404:17)
    at run_all (chunk-V75KQ2P3.js?v=f7139a43:68:11)
    at run_micro_tasks (chunk-V75KQ2P3.js?v=f7139a43:467:3)
(anonymous) @ chunk-ANGXYLDB.js?v=f7139a43:1404
run_all @ chunk-V75KQ2P3.js?v=f7139a43:68
run_micro_tasks @ chunk-V75KQ2P3.js?v=f7139a43:467

```

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Create a kind cluster
2. Go to the pods page
3. Select projectcontour namespace

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MarsKubeX**
### What does this PR do?
This PR added a different key for  "each loop" for containers in pods list when Id is not provided. This can occur when containers are in being created or in "waiting" status making duplication of pods in pods list.

### What issues does this PR fix or reference?

fixes #13048 

### How to test this PR?

1. Create a kind cluster
2. Go to pods page
3. Select projectcontour namespace
4. When creating or, for example, deleting multiple pods, the list of pods should never contain duplicates.

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by simonrey1** [comment]
I found another loop in `packages/renderer/src/lib/pod/PodmanPodDetailsSummary.svelte` that relies on this id.

File: packages/renderer/src/lib/ui/Dots.svelte [hunk 1]
```diff
@@ -19,7 +19,7 @@ $: organizedContainers = organizeContainers(containers);
   {/each}
 {:else}
   {#each Object.entries(organizedContainers) as [status, c] (status)}
-    {#each c as container (container.Id)}
+    {#each c as container (container.Id || `${container.Names}-${status}`)}
```
Comment (simonrey1) [inline packages/renderer/src/lib/ui/Dots.svelte]: Suggestion: `{#each c as container, i (i)}`

Comment (SoniaSandler) [reply packages/renderer/src/lib/ui/Dots.svelte]: +1, when we added the explicit keys to the `#each` loops in svelte, we used a single known unique property of the items or if we couldn't find something like that, we used the index of the loop since it is already used under the hood by svelte when there is no explicit key for the loop

**Comment by MarsKubeX** [comment]
> I found another loop in `packages/renderer/src/lib/pod/PodmanPodDetailsSummary.svelte` that relies on this id.

 @eqqe I'll test this separately and create another issue if it's also a bug, since it's outside the scope of this PR.

File: packages/renderer/src/lib/ui/Dots.svelte (hunk 1 above)
Comment (MarsKubeX) [reply packages/renderer/src/lib/ui/Dots.svelte]: Changed to use the index as a key

**Review by gastoner — APPROVED** [review]
LGTM, dont see duplicates

**Review by SoniaSandler — APPROVED** [review]
Sorry, forgot to click the submit review button 😅
