### PR TITLE
fix(container-registry): handle provider failures gracefully in podmanListImages

### LINKED ISSUE #16327: bug(listImages): podman desktop does not display images if one connection is throwing an error
### Bug description

When dealing with multiple connections, if one connection is failing, the `window.listImages` is failing completely.

We may want to do something like Promise.allSettle, and at least display the images we got from the working connection, and log the problematic ones.

### Operating system

All

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sheikhlimon**
### What does this PR do?
When one provider connection fails, podmanListImages now continues to return images from working providers instead of failing.

### What issues does this PR fix or reference?
Fixes #16327 

### AI Assistance
- [x] This PR was created or reviewed with AI assistance

### How to test this PR?

- Added unit test: `expect podmanListImages to return images from working providers even if one fails.`

Tested locally with an SSH provider that was unreachable (simulated by blocking port 22 with iptables and killing the SSH tunnel):
 
```bash                                                                                                                        
[DEBUG] Processing provider: Podman (podman.mylocalSSH)
[DEBUG] Error listing images from provider Podman (podman.mylocalSSH): Error: connect ECONNREFUSED /tmp/podman-remote-mylocalSSH.sock
[DEBUG] Total images returned: 4
```
Images from the 3 working providers are displayed correctly.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by sheikhlimon** [comment]
@simonrey1  Would you be able to test this with your SSH setup when you get a chance? Really appreciate your help investigating this issue.                                 
   
Also, CodeRabbit pointed out a pre-existing issue on line 669 where the Docker API fallback hardcodes `{ all: false}` instead of passing through the options. Would you prefer I fix that in this PR or address it in a follow-up?

**Comment by simonrey1** [comment]
> @simonrey1 Would you be able to test this with your SSH setup when you get a chance? Really appreciate your help investigating this issue.

Edit:

Hello,

After trying today:

- When the remote recently went to sleep: the list of images is not displayed during 3mn, before the connection actually timeouts, throws and exception, but the whole request is done again and the images are displayed again. It is almost the same behaviour as the main branch.

- Sorry about misleading you, but maybe your fix yesterday introducing a shorter timeout (maybe 15s ?) to list the images would be better, because here we are stuck with the interface not showing anything during 3 long minutes.

**Comment by simonrey1** [comment]
> Also, CodeRabbit pointed out a pre-existing issue on line 669 where the Docker API fallback hardcodes { all: false} instead of passing through the options. Would you prefer I fix that in this PR or address it in a follow-up?

Please open an issue, and you can follow-up if you have some spare time.
Thanks a lot for your contributions, it is much welcomed in this community 💓

**Comment by sheikhlimon** [comment]
> > @simonrey1 Would you be able to test this with your SSH setup when you get a chance? Really appreciate your help investigating this issue.
> 
> Edit:
> 
> Hello,
> 
> After trying today:
> 
> * When the remote recently went to sleep: the list of images is not displayed during 3mn, before the connection actually timeouts, throws and exception, but the whole request is done again and the images are displayed again. It is almost the same behaviour as the main branch.
> * Sorry about misleading you, but maybe your fix yesterday introducing a shorter timeout (maybe 15s ?) to list the images would be better, because here we are stuck with the interface not showing anything during 3 long minutes.

Thanks for testing again!                                                                                         
                                                                                                                         
I understand - the try-catch alone handles the error case, but for sleeping remotes we need faster feedback than the default 3-minute timeout.                                                                                              
                                                                                                                         
I was thinking a 10-second timeout might provide a good balance between responsiveness and giving slow connections time to respond. Curious what you think - would 10s work, or do you prefer 15s?

**Comment by sheikhlimon** [comment]
> Please open an issue, and you can follow-up if you have some spare time.
> Thanks a lot for your contributions, it is much welcomed in this community 💓

will open a separate issue for the follow-up.

Thank you for being so welcoming! I love contributing and it's really rewarding when others get value from my code.

**Comment by simonrey1** [comment]
> I was thinking a 10-second timeout might provide a good balance between responsiveness and giving slow connections time to respond. Curious what you think - would 10s work, or do you prefer 15s?  

I am not not sure: if this is working for some people taking 30s for instance, I don't want to break it for them with a 10 or a 15s timeout. I think we should discuss that internally first.

**Comment by sheikhlimon** [comment]
> I am not not sure: if this is working for some people taking 30s for instance, I don't want to break it for them with a 10 or a 15s timeout. I think we should discuss that internally first.

Fair point! Even with the try-catch, users with slow connections would lose images from providers that take longer than the timeout.

Let's wait for your internal discussion to figure out the right approach.

**Comment by simonrey1** [comment]
> > I am not not sure: if this is working for some people taking 30s for instance, I don't want to break it for them with a 10 or a 15s timeout. I think we should discuss that internally first.
> 
> Fair point! Even with the try-catch, users with slow connections would lose images from providers that take longer than the timeout.
> 
> Let's wait for your internal discussion to figure out the right approach.

I did not get much feedback internally but it seems that a 30s timeout should be ok.

**Comment by sheikhlimon** [comment]
Sounds good to me 👍

**Comment by sheikhlimon** [comment]
@simonrey1 I've implemented the 30s timeout on `listImages`. This should handle the sleeping SSH case you tested.                                                

One thing I noticed: the manifest inspection (`podmanInspectManifest`) happens after `listImages` and isn't covered by the timeout. If that hung, it could block a provider's response. This is pre-existing behavior, but let me know if you'd like the timeout to cover the full provider processing (list + inspect) or just the initial `listImages` call.

**Comment by simonrey1** [comment]
Ok so I put the remote computer to sleep, refreshed Podman Desktop, saw no images during 30s, and then my local images appeared, with this message in the console. 

Screenshot 2026-03-04 at 17 26 13

So it seems that the timeout worked :)

**Review by simonrey1 — APPROVED** [review]
LGTM (see my comment here https://github.com/podman-desktop/podman-desktop/pull/16404#issuecomment-3998646019)

Waiting for another review to validate this 30s timeout approach. Raised the issue in a meeting but we could not take a decision.

nitpick: the withTimeout could be a global helper? Here it has a specific message for the provider, but the logic could be reused. Maybe it already exists.

**Comment by sheikhlimon** [comment]
> Waiting for another review to validate this 30s timeout approach. Raised the issue in a meeting but we could not take a decision.

Understood!

> nitpick: the withTimeout could be a global helper? Here it has a specific message for the provider, but the logic could be reused. Maybe it already exists.

Good call! I just searched through `packages/main/src` and there's actually no global timeout helper yet.

There's a few other places using inline `Promise.race` timeouts (like `extension-loader.ts`), so extracting a shared utility makes sense. Want me to pull it out into a global helper in this PR, or keep it as a follow-up?

**Comment by simonrey1** [comment]
> There's a few other places using inline `Promise.race` timeouts (like `extension-loader.ts`), so extracting a shared utility makes sense. Want me to pull it out into a global helper in this PR, or keep it as a follow-up?

Let's keep it as a follow-up :) Thanks a lot for checking it.

**Comment by simonrey1** [comment]
Hello @sheikhlimon,

Discussing with the team today, we think the 30s should probably be configurable in a setting.
We would prefer to have this setting before merging the PR if that does not bother you?

I can help (Paris Time) if you want.

**Comment by sheikhlimon** [comment]
> Discussing with the team today, we think the 30s should probably be configurable in a setting. We would prefer to have this setting before merging the PR if that does not bother you?
> 
> I can help (Paris Time) if you want.

Thanks! I took a look at the codebase and I think I have a plan:

1. Create a `container-registry-init.ts` file (similar to `registry-init.ts`) to register the provider timeout configuration as a number type with min/max values
2. Update `container-registry.ts` to read the timeout from configuration instead of the hardcoded value
3. Register the init in `index.ts`
4. Add a test for reading the config value

Does this approach sound right to you?

I'd appreciate your guidance on:

- whether `preferences.container` is the right section/ID to use
- if there are existing patterns for number-type settings I should reference
- the best way to test this

I'm based in Bangladesh (UTC+6) and usually available in the evenings (8 PM – 3 AM my time), which may overlap with your afternoons in Paris.

**Comment by simonrey1** [comment]
> Thanks! I took a look at the codebase and I think I have a plan:
> 
> 1. Create a `container-registry-init.ts` file (similar to `registry-init.ts`) to register the provider timeout configuration as a number type with min/max values

Yes, it is a good starting point. Note the properties are named with an interpolation of enumeration values, and you can do the same.

```ts
 properties: {
        [`${PreferredRegistriesSettings.SectionName}.${PreferredRegistriesSettings.Preferred}`]: {
```

Yes you can use a number with min/max values, see this other example:

packages/main/src/plugin/extension/extension-loader.ts
```ts
    const maxActivationTimeConfiguration: IConfigurationNode = {
      id: 'preferences.extensions',
      title: 'Extensions',
      type: 'object',
      properties: {
        [ExtensionLoaderSettings.SectionName + '.' + ExtensionLoaderSettings.MaxActivationTime]: {
          description: 'Maximum activation time for an extension, in seconds.',
          type: 'number',
          default: DEFAULT_TIMEOUT,
          minimum: 1,
          maximum: 100,
        },
      },
    };
```

> 2. Update `container-registry.ts` to read the timeout from configuration instead of the hardcoded value

LGTM

> 3. Register the init in `index.ts`

Ok

> 4. Add a test for reading the config value

Yes

> Does this approach sound right to you?

LGTM

> 
> I'd appreciate your guidance on:
> 
> * whether `preferences.container` is the right section/ID to use

Overall it is just a timeout preference for local/remote container engines, so I think it is ok under this id.

> * if there are existing patterns for number-type settings I should reference

See the example above with `maxActivationTimeConfiguration`

> * the best way to test this

Add unit tests, and if you have another laptop with Linux, you can open SSH and connect remotely.

Whata I did:
```sh
podman system connection add my-remote --identity ~/.ssh/id_ed25519 ssh://<your_remote_username>@192.168.1.<your_remote_local_ip>:22/run/user/1000/podman/podman.sock
```

And also make sure to enable remotes in the settings of the podman extension.


> I'm based in Bangladesh (UTC+6) and usually available in the evenings (8 PM – 3 AM my time), which may overlap with your afternoons in Paris.

Ok, we will keep it async for now but we will organize a meeting if needed.

**Comment by sheikhlimon** [comment]
@simonrey1 I've implemented the configurable timeout setting. Here's what I did:

1. Created `packages/api/src/container-registry-settings.ts` with `ContainerRegistrySettings` enum and `DEFAULT_PROVIDER_TIMEOUT` constant
2. Added `init()` method to `ContainerProviderRegistry` that registers the configuration
3. Updated `podmanListImages()` to read timeout from the configuration
4. Called `containerProviderRegistry.init()` in `index.ts`
5. Added a unit test to verify the configuration is registered correctly

The setting is available under `container.providerTimeout` with:
- Default: 30 seconds
- Min: 5 seconds
- Max: 120 seconds

All 172 tests pass ✅

I wasn't able to manually test with a remote SSH connection since I don't have a second machine, but I've added unit tests to verify the functionality. Would appreciate it if you could test when you get a chance!

Let me know if you'd like any changes!

screenshot-2026-03-07_07-09-11

**Comment by sheikhlimon** [comment]
Should I address CodeRabbit's config validation comment, or is the schema min/max enough?

File: packages/main/src/plugin/container-registry.ts [hunk 1]
```diff
@@ -642,6 +663,33 @@ export class ContainerProviderRegistry {
   // Podman list images will prefer to use libpod API of the provider
   // before falling back to using the regular API
   async podmanListImages(options?: PodmanListImagesOptions): Promise<ImageInfo[]> {
+    // Get timeout from configuration
+    const timeoutSeconds = this.configurationRegistry
+      .getConfiguration(ContainerRegistrySettings.SectionName)
+      .get<number>(ContainerRegistrySettings.ProviderTimeout, DEFAULT_PROVIDER_TIMEOUT);
```
Comment (simonrey1) [inline packages/main/src/plugin/container-registry.ts:671]: remark: the setting already has the `DEFAULT_PROVIDER_TIMEOUT` (packages/main/src/plugin/container-registry.ts l.156). I think we should not export it and apply it here again, I think this default should be scoped to container-registry only, who will be responsible for propagating it here when we get the config.

**Review by simonrey1 — COMMENTED** [review]
LGTM

Thanks for taking the time to solve this issue.

Before merging, please let's try my remark https://github.com/podman-desktop/podman-desktop/pull/16404/changes#r2903995914.

We should also create a follow-up issue (if non existing) to display a loader instead of "no images".

File: packages/main/src/plugin/container-registry.ts [hunk 2]
```diff
@@ -642,6 +663,33 @@ export class ContainerProviderRegistry {
...
+    const PROVIDER_TIMEOUT_MS = timeoutSeconds * 1000;
```
[the remark this answers is not in the document]
Comment (simonrey1) [reply packages/main/src/plugin/container-registry.ts]: No it is ok, we believe the min max here are respected for other settings too

**Comment by simonrey1** [comment]
> Should I address CodeRabbit's config validation comment, or is the schema min/max enough?

I answered it, I think it does not need to be addressed. In this case the min max values are enough honestly.

File: packages/main/src/plugin/container-registry.ts (hunk 1 above)
Comment (sheikhlimon) [reply packages/main/src/plugin/container-registry.ts:671]: Ah, you're right! I was following the extension-loader pattern at first, but it does make more sense to keep this scoped to container-registry only. I've removed the export.

Should we consider doing the same for extension-loader-settings.ts down the line, or is there a reason it's exported there?

**Comment by sheikhlimon** [comment]
> Before merging, please let's try my remark https://github.com/podman-desktop/podman-desktop/pull/16404/changes#r2903995914.

Linking the response here for reference: https://github.com/podman-desktop/podman-desktop/pull/16404#discussion_r2912020759

> We should also create a follow-up issue (if non existing) to display a loader instead of "no images".

Will do. That makes three follow-ups. I’ve already opened an issue for the Docker API and will make a PR soon. still need to create ones for the helper function and to display a loader.

File: packages/main/src/plugin/container-registry.ts (hunk 1 above)
Comment (simonrey1) [reply packages/main/src/plugin/container-registry.ts:671]: Oh well, I did not see that one.
I discussed with the author of this constant (@axel7083) and he likes to export it to use it in tests for instance.
But I think we should keep it as it as a small technical debt it is ok.

Comment (simonrey1) [reply packages/main/src/plugin/container-registry.ts:671]: But my point is that we should also not use it in 

```ts

 const timeoutSeconds = this.configurationRegistry
      .getConfiguration(ContainerRegistrySettings.SectionName)
      .get<number>(ContainerRegistrySettings.ProviderTimeout, DEFAULT_PROVIDER_TIMEOUT);
```

and replace it with

```ts
 const timeoutSeconds = this.configurationRegistry
      .getConfiguration(ContainerRegistrySettings.SectionName)
      .get<number>(ContainerRegistrySettings.ProviderTimeout);
```

So that the responsability of the default value is only in the configuration init.

Comment (sheikhlimon) [reply packages/main/src/plugin/container-registry.ts:671]: Got it! I initially removed it, but CodeRabbit flagged it. After looking into it a bit more, I thought it might be better to keep it as a defensive measure.

**Comment by sheikhlimon** [comment]
@simonrey1 Done! Kept the export and removed it from `.get()` so the default is only in the configuration registration. Thanks!

Edit: Just to confirm - is the export okay to keep for this PR, or should I remove it as well?

**Comment by simonrey1** [comment]
> Edit: Just to confirm - is the export okay to keep for this PR, or should I remove it as well?

Please also remove it as it is only used in your file, please set the default value inline.

Thanks a lot for the changes you have made. Testing it right now and giving you an approval soon.

File: packages/main/src/plugin/container-registry.ts [hunk 3]
```diff
@@ -642,6 +663,33 @@ export class ContainerProviderRegistry {
   // Podman list images will prefer to use libpod API of the provider
   // before falling back to using the regular API
   async podmanListImages(options?: PodmanListImagesOptions): Promise<ImageInfo[]> {
+    // Get timeout from configuration
+    const timeoutSeconds = this.configurationRegistry
+      .getConfiguration(ContainerRegistrySettings.SectionName)
+      .get<number>(ContainerRegistrySettings.ProviderTimeout);
+    const PROVIDER_TIMEOUT_MS = timeoutSeconds * 1000;
```
Comment (simonrey1) [inline packages/main/src/plugin/container-registry.ts]: nitpick: normally this case is reserved for global constants, here it can change with a param, please use camelCase 👍

**Review by simonrey1 — APPROVED** [review]
LGTM
The image list is displayed with my local images after 30s if the remote podman machine has gone to sleep recently. The 30s value is configurable (tried 60s) and it worked too.
Left some nitpicks.

Question to UX: @vancura @MariaLeonova, here we introduce a new param and a entire new page appears, I want to validate if that is ok or not?

Image

**Comment by sheikhlimon** [comment]
@simonrey1 I believe the ci is failing because `timeoutSeconds` could be `undefined` when accessing it on line 672:   
                              
```ts
const providerTimeoutMs = timeoutSeconds * 1000;  // TypeScript error: possibly undefined
```       
                                                          
How should I handle this without using `!`?

Edit: 
> Please also remove it as it is only used in your file, please set the default value inline.

To fix the typecheck error, I was thinking of doing something like:

```
const providerTimeoutMs = (timeoutSeconds ?? value) * 1000;
```

You also mentioned using the value inline - does that mean removing the constant entirely?

For example:
```
default: 30,
const providerTimeoutMs = (timeoutSeconds ?? 30) * 1000;
```

Since the value would then be used in two places, would it make more sense to keep it as a constant instead of repeating `30`?

Let me know if that makes sense.

**Comment by MariaLeonova** [comment]
> Question to UX: @vancura @MariaLeonova, here we introduce a new param and a entire new page appears, I want to validate if that is ok or not?

@simonrey1 @sheikhlimon can you please help me understand why the section in preferences is called Container, while the issue is to do with providers?
Maybe there's a more intuitive name for it? Or does it make sense?

**Comment by sheikhlimon** [comment]
> @simonrey1 @sheikhlimon can you please help me understand why the section in preferences is called Container, while the issue is to do with providers?
> Maybe there's a more intuitive name for it? Or does it make sense?

Good question. I initially suggested using `preferences.container` and asked @simonrey1 for guidance. He agreed that it makes sense there since it’s essentially a timeout preference for local/remote container engines.

That said, I can see your UX point - “Provider” might feel more intuitive since this setting is tied to provider connections. If the team thinks `preferences.provider` would be clearer, I’m happy to update it.

**Comment by simonrey1** [comment]
> @simonrey1 I believe the ci is failing because `timeoutSeconds` could be `undefined` when accessing it on line 672:
> 
> ```ts
> const providerTimeoutMs = timeoutSeconds * 1000;  // TypeScript error: possibly undefined
> ```
> 
> How should I handle this without using `!`?
> 
> Edit:
> 
> > Please also remove it as it is only used in your file, please set the default value inline.
> 
> To fix the typecheck error, I was thinking of doing something like:
> 
> ```
> const providerTimeoutMs = (timeoutSeconds ?? value) * 1000;
> ```
> 
> You also mentioned using the value inline - does that mean removing the constant entirely?
> 
> For example:
> 
> ```
> default: 30,
> const providerTimeoutMs = (timeoutSeconds ?? 30) * 1000;
> ```
> 
> Since the value would then be used in two places, would it make more sense to keep it as a constant instead of repeating `30`?
> 
> Let me know if that makes sense.

Oh I see that typescript does not know about the default value.

I think you can go back to your original solution with the unexported constant on top of the file, and providing it as the default value in both the config and the getter. I am sorry as I did not know about this limitation.

**Comment by simonrey1** [comment]
> > Question to UX: @vancura @MariaLeonova, here we introduce a new param and a entire new page appears, I want to validate if that is ok or not?
> 
> @simonrey1 @sheikhlimon can you please help me understand why the section in preferences is called Container, while the issue is to do with providers? Maybe there's a more intuitive name for it? Or does it make sense?

No I am not attached to the "Container" section name, we could go with "Providers" or anything more intuitive. I checked the existing sections and could not find one to add this param though.

NB: The file name where is the option is stored is "container-registry" so it might be a good starting point.
What if we go with a "Container registry" or (registries) configuration section?

**Comment by MariaLeonova** [comment]
> What if we go with a "Container registry" or (registries) configuration section?


I think multiple 'registries' would make more sense here! So the title would be `Container registries`.

**Comment by sheikhlimon** [comment]
> I think multiple 'registries' would make more sense here! So the title would be `Container registries`.

@MariaLeonova @simonrey1, Quick question on naming consistency. You suggested `Container registries` (plural) for the section title, but I have some places currently using singular `container-registry`:
1. File name: `container-registry-settings.ts`
2. SectionName enum value: `SectionName = 'container-registry'`
3. Config ID: `id: 'preferences.container-registry'`

Should I update all of these to plural `container-registries` to match the title?
For example:
- `container-registries-settings.ts`
- `SectionName = 'container-registries'`
- `id: 'preferences.container-registries'`

Or is the singular naming in code files okay even though the UI title is plural?

**Comment by simonrey1** [comment]
> > I think multiple 'registries' would make more sense here! So the title would be `Container registries`.
> 
> @MariaLeonova @simonrey1, Quick question on naming consistency. You suggested `Container registries` (plural) for the section title, but I have some places currently using singular `container-registry`:
> 
> 1. File name: `container-registry-settings.ts`
> 2. SectionName enum value: `SectionName = 'container-registry'`
> 3. Config ID: `id: 'preferences.container-registry'`
> 
> Should I update all of these to plural `container-registries` to match the title? For example:
> 
> * `container-registries-settings.ts`
> * `SectionName = 'container-registries'`
> * `id: 'preferences.container-registries'`
> 
> Or is the singular naming in code files okay even though the UI title is plural?

I would be prefer to keep the singular naming in code files, and only the UI title plural to limit the changes.

**Comment by sheikhlimon** [comment]
Updated the section to use id: 'preferences.container-registry' with title: 'Container registries' as discussed. Kept the internal naming (file, enum) singular.

**Review by simonrey1 — APPROVED** [review]
LGTM (see previous comments for details)
