### PR TITLE
fix: updated the network create icon

### LINKED ISSUE #14971: Create Network icon differs from other network icons
### Bug description

See the screenshot:

Image

The Network icon in the navbar is correct (the atom-like blob), but the icon in the create flow is different (looks like ethernet-connected computers, which is wrong).

Can somebody please fix this?

/cc @SoniaSandler and @MariaLeonova for visibility

### Operating system

—

### Installation Method

None

### Version

1.23.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bmahabirbu**
### What does this PR do?

See above

### Screenshot / video of UI

Screenshot From 2025-11-24 14-35-20

### What issues does this PR fix or reference?

Fixes: https://github.com/podman-desktop/podman-desktop/issues/14971

### How to test this PR?

- [] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by bmahabirbu** [comment]
@vancura please take a look!

**Review by vancura — APPROVED** [review]
Looks great, thanks!

**Review by simonrey1 — APPROVED** [review]

**Review by axel7083 — CHANGES_REQUESTED** [review]
Image

The volume icon is 40x40 where the Network Icon is 48x48

cc @vancura what would you recommend for the sizing?

File: packages/renderer/src/lib/network/CreateNetwork.svelte [hunk 1]
```diff
@@ -118,7 +117,7 @@ let hasInvalidFields = $derived(!networkInfo.networkName || !networkInfo.selecte
   title="Create a Network"
   showEmptyScreen={providerConnections.length === 0 && !createNetworkInProgress}>
   {#snippet icon()}
-    <Icon icon={faNetworkWired} class="fa-2x" />
+    <NetworkIcon size="48" />
```
Comment (gastoner) [inline packages/renderer/src/lib/network/CreateNetwork.svelte]: I believe you should be able to do: 
`<Icon icon={NetworkIcon} class="fa-2x" />` you should be able to pass to the icon string e.g. fas-fa-foo-bar / faFooBar (imported from fontawesome like it was done previously) or add Svelte component

**Review by gastoner — COMMENTED** [review]
See coments

File: packages/renderer/src/lib/network/CreateNetwork.svelte (hunk 1 above)
Comment (gastoner) [reply packages/renderer/src/lib/network/CreateNetwork.svelte]: Maybe the `size` should be specified rather than class (but not sure rn what makes uses of this svelte component) with 2x/md or so not sure rn

Comment (gastoner) [reply packages/renderer/src/lib/network/CreateNetwork.svelte]: cc @bmahabirbu

**Comment by vancura** [comment]
The icon is saved as SVG, it should scale nicely for any resolution, well up from 32×32.

File: packages/renderer/src/lib/network/CreateNetwork.svelte (hunk 1 above)
Comment (gastoner) [reply packages/renderer/src/lib/network/CreateNetwork.svelte]: image

`<Icon icon={NetworkIcon} class="2x" />`

cc @axel7083

Comment (bmahabirbu) [reply packages/renderer/src/lib/network/CreateNetwork.svelte]: Nice!

File: packages/renderer/src/lib/network/CreateNetwork.svelte [hunk 2]
```diff
@@ -163,7 +163,6 @@ let hasInvalidFields = $derived(!networkInfo.networkName || !networkInfo.selecte
           disabled={hasInvalidFields || createNetworkInProgress}
           inProgress={createNetworkInProgress}
           class="w-full"
-          icon={faNetworkWired}
```
Comment (gastoner) [inline packages/renderer/src/lib/network/CreateNetwork.svelte:166]: I think you can also pass the NetworkIcon

**Review by axel7083 — APPROVED** [review]
LGTM

File: packages/renderer/src/lib/network/CreateNetwork.svelte (hunk 2 above)
Comment (bmahabirbu) [reply packages/renderer/src/lib/network/CreateNetwork.svelte:166]: Good catch!

Comment (bmahabirbu) [reply packages/renderer/src/lib/network/CreateNetwork.svelte:166]: image
Actually the icon looks out of place here and we already have it up above. So I think that ill keep it removed thoughts @gastoner?

Comment (gastoner) [reply packages/renderer/src/lib/network/CreateNetwork.svelte:166]: Oh yes, just remove it then

**Review by gastoner — APPROVED** [review]
