### PR TITLE
fix: make container or vm connection terminal responsive on start and restart

### LINKED ISSUE #81: Terminal does not show when starting / restarting on details page
https://github.com/user-attachments/assets/24b34507-a36d-40ba-9b77-afb32c89ae75

When pressing on details and then starting the image, it does not automatically show the terminal.

There's no logs for errors.

I have to go back to resources and re-enter the terminal for it to appear.

### LINKED ISSUE #11983: terminal not responding after restart
### Bug description

When the user is in the terminal's page for a podman machine, and it restarts the podman machine, the terminal disappears and reappears after the machine is restarted, but the terminal is not responding.

### Operating system

mac

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
### What does this PR do?
When starting or restarting a container connection or a vm connection from the terminal page, the terminal is not responsive. This fixes this issue and the resizing problem that happens when starting the connection for the first time from the terminal page.

### What issues does this PR fix or reference?
Fixes https://github.com/redhat-developer/podman-desktop-rhel-ext/issues/81
Fixes https://github.com/podman-desktop/podman-desktop/issues/11983

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesConnectionDetailsTerminal.svelte [hunk 1]
```diff
@@ -25,15 +25,15 @@ interface ProviderDetailsTerminalProps {
...
 let sendCallbackId: number | undefined;
 let terminalContent: string = '';
 let serializeAddon: SerializeAddon;
 let lastState = $state<ProviderConnectionStatus>('started');
+let terminalOnDataListener: IDisposable | undefined = undefined;
 
 $effect(() => {
   const connectionStatus = connectionInfo.status;
-  if (lastState === 'stopped' && connectionStatus === 'started') {
+  if (lastState === 'starting' && connectionStatus === 'started') {
```
Comment (feloy) [inline packages/renderer/src/lib/preferences/PreferencesConnectionDetailsTerminal.svelte]: I would keep the `stopped` one, which can be useful in other cases (I can see this component is not limited to VMs).
Perhaps `connectionStatus === 'started' && connectionStatus !== lastState` ?

**Review by MarsKubeX — APPROVED** [review]
LGTM not tested

**Review by feloy — APPROVED** [review]
LGTM, tested on mac, I can go to the terminal page when the VM is down, then start the VM, and the terminal works correctly when the VM is started
