### PR TITLE
fix: support  all characters in args of command passed to osascript

### LINKED ISSUE #15582: calling exec in admin mode on macOS with spaces in args fails
### Bug description

On MacOS, when using the `process.exec` method from the extension API in admin mode, and passing args with special characters (spaces, etc), the command fails.

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

- Clone the extension https://github.com/feloy/podman-desktop-bug-exec-admin/
- Run Podman Desktop with this extension
- Look at the console, you get:

```
non admin: OK
admin:
```

You should get:
```
non admin: OK
admin: OK
```

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Escape special characters in the args inside the AppleScript called by osascript

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes #15582 

### How to test this PR?

- See steps to reproduce in #15582 
- try with other commands, in the extension, containing special characters (space, quote, backslash)

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/util/exec.ts [hunk 1]
```diff
@@ -123,11 +123,11 @@ export class Exec {
           sudo.exec(sudoCommand, sudoOptions, callback);
```
Comment (axel7083) [inline packages/main/src/plugin/util/exec.ts:123]: nitpick: please update the copyright to 2023-2026

https://github.com/podman-desktop/podman-desktop/blob/4e593f229ef58dfdcb28682d79b138a8eddb262f/packages/main/src/plugin/util/exec.ts#L2

**Review by axel7083 — COMMENTED** [review]
Cannot test as I only have a Linux & Windows computer -

**Comment by benoitf** [comment]
I used the patches from https://github.com/podman-desktop/podman-desktop/pull/15568 + from this PR and I used the case I paste in https://github.com/podman-desktop/podman-desktop/pull/15568 review and it's working fine with this fix

**Review by benoitf — APPROVED** [review]
works on my end, thanks

**Review by jeffmaury — APPROVED** [review]
Tested witk @axel7083 PR on MacOS with RHEL extension bundled into the binary and it is fixed now
