### PR TITLE
fix: migrate Tooltip component to Floating UI for proper positioning

### LINKED ISSUE #13460: Tooltip component may cause scrolling/layout issues when its content is too wide or gets outside of the window's boundaries
### Bug description

Noticed scrolling on CLI Tools Preferences page when everything seems to be perfectly fit into Podman Desktop window. 

Image

Which turned out to be invisible Tooltip component for the compose installation path

Image

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Uninstall Compose CLI
2. Request installation but cancel it when password is requested
3. Restart PD
4. Open CLI Tools Preferences page and make window width smaller until horizontal scrolling appears 

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?

This PR migrates the Tooltip component from CSS-based positioning to Floating UI library to fix tooltip clipping and scrolling issues at window edges. Used `@floating-ui/dom` for smart tooltip positioning with flip, shift, and offset value. Added max-width (400px) with proper text wrapping for long content. Implemented dynamic positioning that automatically adjusts based on viewport boundaries.

### Screenshot / video of UI

Example how long Tooltip's content is displayed on the page:

### What issues does this PR fix or reference?

#13460 

### How to test this PR?

- Hover over tooltip with very long text content
- Verify text wraps at 400px max-width
- Verify no text clipping at window edges

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/ui/src/lib/tooltip/Tooltip.svelte [hunk 1]
```diff
@@ -78,6 +78,8 @@ async function updateTooltipPosition(): Promise<void> {
     ],
   });
 
+  if (!tooltipElement) return;
```
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.svelte:91]: remark: it seems to already be checked on line 67, why is it needed to add this if condition?

File: packages/renderer/src/lib/image/BuildImageFromContainerfileCard.spec.ts [hunk 2]
```diff
@@ -79,8 +79,11 @@ test('Expect default tooltip', async () => {
     icon: undefined,
   });
 
-  // check we have a div tooltip with aria-label tooltip
-  const tooltip = screen.getByText('Default platform of your computer');
+  const tooltipSlot = container.querySelector('.tooltip-slot');
```
Comment (simonrey1) [inline packages/renderer/src/lib/image/BuildImageFromContainerfileCard.spec.ts]: question: Could we define an role for this tooltip slot to avoid selecting by classname?

File: packages/ui/src/lib/tooltip/Tooltip.svelte (hunk 1 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.svelte:91]: Added a small comment in the code. It's just a double check that our element has not been unmounted during the position computation with calling above asynchronous function.

**Comment by simonrey1** [comment]
Screenshot 2025-10-13 at 13 16 50

I wonder why I am the only human reviewer on this one? Could you add more people from the team please?

File: packages/renderer/vite.tests.setup.js [hunk 3]
```diff
@@ -74,3 +74,13 @@ for (const methodName of methodNames) {
     writable: true,
   });
 }
+
+// Mock ResizeObserver for @floating-ui/dom
+class ResizeObserverMock {
```
Comment (simonrey1) [inline packages/renderer/vite.tests.setup.js:79]: Thanks for adding this mock in the renderer tests. I think it is a good idea to have it available globally. However I see that one test is already implementing this mock:

packages/renderer/src/lib/help/HelpActions.spec.ts

Could you ensure that there is only one implementation of this mock please?

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts [hunk 4]
```diff
@@ -18,32 +18,270 @@
...
+  await tick();
+  expect(screen.queryByText('hover text')).toBeInTheDocument();
+
+  await fireEvent.mouseLeave(slot!);
+  await tick();
+  expect(screen.queryByText('hover text')).not.toBeInTheDocument();
+});
+
+test('tooltip respects top placement prop', async () => {
+  const { computePosition } = await import('@floating-ui/dom');
```
Comment (axel7083) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: question: why do you use a dynamic import here?

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts [hunk 5]
```diff
@@ -18,32 +18,270 @@
...
+});
+
+test('tooltip shows on mouse enter and hides on mouse leave', async () => {
+  const { container } = render(TooltipTestComponent, { tip: 'hover text' });
+
+  const slot = container.querySelector('.tooltip-slot');
+
+  expect(screen.queryByText('hover text')).not.toBeInTheDocument();
+
+  await fireEvent.mouseEnter(slot!);
```
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: suggestion: you can also `assert(slot)` before and typescript will have it defined removing the need to use `!`

Comment (axel7083) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]:
```
import { assert } from 'vitest'
```

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts [hunk 6]
```diff
@@ -18,32 +18,270 @@
...
+
+test('tooltip handles tipSnippet prop', async () => {
+  const TestComponent = await import('./TooltipTestWithSnippet.svelte');
+  const { container } = render(TestComponent.default);
+
+  const slot = container.querySelector('.tooltip-slot');
+  await fireEvent.mouseEnter(slot!);
+  await tick();
+
+  expect(screen.queryByText('Custom snippet content')).toBeInTheDocument();
```
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: remark: lately I have seen more `waitFor` instead of `await tick();` in the Podman-Desktop codebase

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts [hunk 7]
```diff
@@ -18,32 +18,270 @@
...
+    return (): void => {};
+  }),
+}));
+
+beforeEach(() => {
+  tooltipHidden.set(false);
+  vi.clearAllMocks();
+});
+
+test('tooltip is hidden when tooltipHidden is true', async () => {
```
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: suggestion: wrap all tests in a describe block, so we can easily run all the tests in the file

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 4 above)
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: suggestion: remove all these dynamic imports with a 

```ts

import { autoUpdate,computePosition } from '@floating-ui/dom';
```

at the top of the file.

I tested and the tests are passing.

Comment (simonrey1) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: linked comment

https://github.com/podman-desktop/podman-desktop/pull/14246#discussion_r2426080337

**Comment by simonrey1** [comment]
Thanks for handling all the feedback comments! I will give it a try tomorrow to test the rendering on my desktop.
If anyone else wants to review also, please do not hesitate.

File: packages/renderer/vite.tests.setup.js (hunk 3 above)
Comment (vzhukovs) [reply packages/renderer/vite.tests.setup.js:79]: removed duplicated mocks

File: packages/renderer/src/lib/image/BuildImageFromContainerfileCard.spec.ts (hunk 2 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/image/BuildImageFromContainerfileCard.spec.ts]: did a bit different approach, not selecting tooltip by selector, selecting with testing id, which works only when unit tests are running

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 4 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: updated with single import instead of dedicated for the each test

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 6 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: updated, used waitFor method instead of tick

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 7 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: moved all tests in a single describe section

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 4 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: updated

**Comment by simonrey1** [comment]
Thanks for the update of the Tooltip. 

I only had an issue when entering a long text through the `tipSnippet` property of the tooltip. It seems that the text does not wrap correctly.

Screenshot 2025-10-16 at 14 34 25

File: packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts [hunk 8]
```diff
@@ -350,12 +350,21 @@ test('Expect tooltip text shows info when input is less than minimum', async ()
     minimum: 1,
     maximum: 34,
   };
-  await awaitRender(record, {});
+  render(PreferencesRenderingItemFormat, {
```
Comment (simonrey1) [inline packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts]: question: why did you change from `awaitRender` to `render()` + `await tick()`?

It seems that it had the same implementation

File: packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts [hunk 9]
```diff
@@ -124,14 +130,17 @@ test('Expect tooltip to include Kubernetes provider connections', () => {
...
-test('Expect tooltip to include VM provider connections', () => {
+test('Expect tooltip to include VM provider connections', async () => {
   providerMock.vmConnections = [
     { name: 'connection 1', status: 'ready' } as unknown as ProviderVmConnectionInfo,
     { name: 'connection 2', status: 'ready' } as unknown as ProviderVmConnectionInfo,
     { name: 'connection 3', status: 'stopped' } as unknown as ProviderVmConnectionInfo,
   ];
   render(ProviderWidget, { entry: providerMock });
 
+  const tooltipTrigger = screen.getByTestId('tooltip-trigger');
```
Comment (simonrey1) [inline packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts:141]: question: why did you add this action in this test? It seems to be testing the same as before?

Comment (vzhukovs) [reply packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts:141]: if I get it right (I mean, the question), tests continue to check the same workflows, but with the modification in the Tooltip component, tooltip triggers to show to the user by mouse enter event, that's why I added here triggering the events to check that we have expected text in tooltip's content

File: packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts (hunk 8 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts]: yep, because of big amount of modified files forgot to update these tests, reverted the original calling of awaitRender method, thx!

**Comment by vzhukovs** [comment]
> Thanks for the update of the Tooltip.
> 
> I only had an issue when entering a long text through the `tipSnippet` property of the tooltip. It seems that the text does not wrap correctly.
> 
> Screenshot 2025-10-16 at 14 34 25

Ohh, this use case didn't check properly. Thanks for pointing to this issue, going to take a look on it, there might be a simple fix, which will provide with the upcoming commit.

File: packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts (hunk 9 above)
Comment (simonrey1) [reply packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts:141]: Ok but I am surprised that before, we did not have to fire this mouse event to see the tooltip?

File: packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts [hunk 10]
```diff
@@ -350,12 +350,19 @@ test('Expect tooltip text shows info when input is less than minimum', async ()
     minimum: 1,
     maximum: 34,
   };
-  await awaitRender(record, {});
+  await awaitRender(record, {
+    initialValue: getInitialValue(record),
```
Comment (simonrey1) [inline packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts]: suggestion: no need to add this line `initialValue: getInitialValue(record),` as it is already done in awaitRender method

Comment (vzhukovs) [reply packages/renderer/src/lib/preferences/PreferencesRenderingItemFormat.spec.ts]: updated

File: packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts (hunk 9 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/statusbar/ProviderWidget.spec.ts:141]: yes, tooltip's visibility operated only with css pseudo classes, e.g. :hover and appeared all the time in DOM, but with the latest modifications now they attaches to the DOM only after mouse enter event on the triggered element. this just need to recalculate the correct display position of tooltip inside the app and show the last one as element with fixed position to avoid showing redundant scrollbars

**Comment by vzhukovs** [comment]
> I only had an issue when entering a long text through the tipSnippet property of the tooltip. It seems that the text does not wrap correctly.

@simonrey1 I've fixed rendering the long text in snippet block, now it should be fine, here below the example of default tooltip and tooltip with long text content:

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts [hunk 11]
```diff
@@ -18,32 +18,295 @@
...
+    await fireEvent.mouseEnter(slot);
+
+    const tooltipContainer = container.querySelector('.tooltip-content');
+    expect(tooltipContainer).toBeInTheDocument();
+  });
+
+  async function renderAndHoverTooltip(props: Record<string, unknown>): Promise<HTMLElement> {
+    const { container } = render(TooltipTestComponent, props);
+
+    const slot = container.querySelector('.tooltip-slot');
```
Comment (simonrey1) [inline packages/ui/src/lib/tooltip/Tooltip.spec.ts]: suggestion(non-blocking): for tests, choose a query selector between "tooltip-slot" class and the getByTestId approach.

**Review by simonrey1 — APPROVED** [review]
LGTM, tested on Mac
The floating-ui lib is a bit heavy in my opinion, but it works!

File: packages/ui/src/lib/tooltip/Tooltip.spec.ts (hunk 11 above)
Comment (vzhukovs) [reply packages/ui/src/lib/tooltip/Tooltip.spec.ts]: updated
