### PR TITLE
fix(kind): use shared temp directory for image push in Flatpak

### LINKED ISSUE #15812: PD fails to push images to kind cluster when running from `flatpak`
### Bug description

Pushing images fails with exit code 1.

### Operating system

linux, Fedora 43

### Installation Method

Installer from website/GitHub releases

### Version

1.25.0

### Steps to reproduce

* Create a kind cluster
* Download any image
* Attempt to push image to kind cluster

### Relevant log output

```shell
[kind] kind extension is active
event is {
  status: 'save',
  id: 'cab8a26f6bdeafa15c579d1b3d2aff691809b39cdce0bd642b503d96e9251af3',
  Type: 'image',
  Action: 'save',
  Actor: {
    ID: 'cab8a26f6bdeafa15c579d1b3d2aff691809b39cdce0bd642b503d96e9251af3',
    Attributes: { image: '', name: '/var/tmp/api.tar1782649932', podId: '' }
  },
  scope: 'local',
  time: 1768913547,
  timeNano: 1768913547251803100
}
```

### Additional context

Image
Image

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?

Fixes image push to Kind cluster failing in Flatpak builds. In Flatpak, `/tmp` is a sandbox-private tmpfs. The image archive was saved inside the sandbox's `/tmp`, but `kind load image-archive` runs on the host via `flatpak-spawn --host` and cannot access it. This PR uses `~/.cache/kind-tmp/` instead, which is shared between the sandbox and host via Flatpak's --`filesystem=home permission`.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

fixes #15812 

### How to test this PR?

1. Build and install Podman Desktop as a Flatpak on Linux
2. Create a Kind cluster: `KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test-cluster`
3. Pull an image in Podman Desktop (e.g. docker.io/library/alpine:latest)
4. Context menu on the image → "Push image to Kind cluster"
5. Verify the push succeeds (previously failed with "Command execution failed with exit code 1")

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by simonrey1 — COMMENTED** [review]
On Asahi Fedora, I installed the flatpak from the build artifact here: https://github.com/podman-desktop/podman-desktop/actions/runs/24097114804/artifacts/6312605975

I also created a kind cluster with the command: `KIND_EXPERIMENTAL_PROVIDER=podman kind create cluster --name test-cluster`

Then from an image → "Push image to Kind cluster"

Unfortunately, I am still seing the "Command execution failed with exit code 1" message.

Image

And in the logs of kind activation:

> main ↪️ [kind] stopping kind extension
> main ↪️ Font podman-desktop.kind-kind-icon.woff2 already registered.
> main ↪️ Icon kind-icon already registered.
> main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
> main ↪️ [kind] Error getting full path Error: Command execution failed with exit code 1
> main ↪️ [kind] kind extension is active

Could you help me with that please?

File: extensions/kind/src/image-handler.ts [hunk 1]
```diff
@@ -16,12 +16,12 @@
  * SPDX-License-Identifier: Apache-2.0
  ***********************************************************************/
 import * as fs from 'node:fs';
+import { join } from 'node:path';
 
 import * as extensionApi from '@podman-desktop/api';
-import { tmpName } from 'tmp-promise';
```
Comment (axel7083) [inline extensions/kind/src/image-handler.ts:21]: is this library still used in other places? If not we should remove it from the package.json.

If we are still using it in other place, can't we get rid of it?

**Review by axel7083 — APPROVED** [review]
LGTM Codewise

File: extensions/kind/src/image-handler.ts (hunk 1 above)
Comment (vzhukovs) [reply extensions/kind/src/image-handler.ts:21]: It still used in other tests, I left it and decided not to remove it completely from the extension, because it will affects other files, which will be out of scope of this issue.

Comment (axel7083) [reply extensions/kind/src/image-handler.ts:21]: Let's create a follow-up issue, and add it to backlog, this library seems pretty useless with recent Node :+1:

Comment (vzhukovs) [reply extensions/kind/src/image-handler.ts:21]: Follow up issue: https://github.com/podman-desktop/podman-desktop/issues/16986
Set low priority.

**Review by feloy — APPROVED** [review]

**Comment by vzhukovs** [comment]
@simonrey1 have you chance to check it according to the flow? I mean, can we merge or it still reproduces on your side?

**Comment by simonrey1** [comment]
> @simonrey1 have you chance to check it according to the flow? I mean, can we merge or it still reproduces on your side?

Not tested with your flow yet.
But what is the issue with the way I tested it?

**Comment by vzhukovs** [comment]
> > @simonrey1 have you chance to check it according to the flow? I mean, can we merge or it still reproduces on your side?
> 
> Not tested with your flow yet. But what is the issue with the way I tested it?

I see the wrong version, displayed on the PD ui. (I thought, that this might be a reason, why kind executable fails on your side.) That's why I asked to double check it, by building directly from sources. I double checked it and this issue seems resolved with this fix.

**Comment by simonrey1** [comment]
> > > @simonrey1 have you chance to check it according to the flow? I mean, can we merge or it still reproduces on your side?
> 
> > 
> 
> > Not tested with your flow yet. But what is the issue with the way I tested it?
> 
> 
> 
> I see the wrong version, displayed on the PD ui. (I thought, that this might be a reason, why kind executable fails on your side.) That's why I asked to double check it, by building directly from sources. I double checked it and this issue seems resolved with this fix.

Thanks you were right, I had two versions installed it seems. 

I am unable to build the flatpak, maybe it is not possible with Asahi Fedora?

I will approve the code only.

**Review by simonrey1 — APPROVED** [review]
LGTM codewise

**Comment by vzhukovs** [comment]
>I am unable to build the flatpak, maybe it is not possible with Asahi Fedora?

Might be, need to investigate this case anyway.
