### PR TITLE
fix: configure startup on login using electron app API

### LINKED ISSUE #10714: podman-desktop.vbs opens on notepad on windows startup
### Bug description

Hello, 
I am noticing  that podman-desktop.vbs opens by itself on windows startup on notepad. Is there any way to avoid this?

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.15.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

This PR changes how automatic startup after login is configured.
Instead of using .vbs file and running it is using electron App API .

I also considered using other ways like:
1.`mklink` to create soft link to `Podman Desktop.exe` - requires administrator privileges and cannot save argument to control window visibility after start
2. .bat file - show cmd command processor window
3. powershell script execution
4. using https://www.npmjs.com/package/registry-js (see https://github.com/akiver/cs-demo-manager/commit/73342962d734bf7125d9382b61e74064805fa334)

### Screenshot / video of UI

https://github.com/user-attachments/assets/811436a5-c4c9-4b67-84bd-b3e4b8480926

### What issues does this PR fix or reference?

Fix #10714.

### How to test this PR?

See the demo above.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/system/windows-startup.ts [hunk 1]
```diff
@@ -94,34 +94,48 @@ export class WindowsStartup {
...
+      $ws = New-Object -ComObject WScript.Shell;
+      $shortcut = $ws.CreateShortcut($env:PD_SHORTCUT);
+      $shortcut.TargetPath = $env:PD;
+      $shortcut.Arguments = $env:ARGS;
+      $shortcut.WorkingDirectory = $env:PD_WD;
+      $shortcut.Description = $env:DESCRIPTION;
+      $shortcut.Save();
+    `;
+
+    const result = spawnSync(
```
[the remark this answers is not in the document]
Comment (dgolovin) [reply packages/main/src/system/windows-startup.ts]: windows-shortcuts is not maintained and was last published 8 years ago.

File: packages/main/src/mainWindow.ts [hunk 2]
```diff
@@ -254,5 +254,6 @@ function isStartedMinimize(): boolean {
   // We convert to string only because sometimes [node] will be the first argument in a packaged
   // environment, so instead of checking each element, simply convert to string and see if --minimize was included.
   const argv = process.argv.toString();
+  console.log(process.argv0);
```
Comment (MarsKubeX) [inline packages/main/src/mainWindow.ts]: Hi @dgolovin! Not blocking. Is this console.log() necesary?

**Review by MarsKubeX — COMMENTED** [review]
Is it possible/interesting to have a unit test for this?

**Comment by dgolovin** [comment]
Looking at using

```
 app.setLoginItemSettings({
    openAtLogin: true,
    path: this.podmanDesktopBinaryPath,
    args: [ minifySettings ],              // e.g. "--minimized"
  });
```

Seems to work the same way, but adding a startup entry to the registry.
I want to test update scenario as well.

File: packages/main/src/system/macos-startup.spec.ts [hunk 3]
```diff
@@ -66,35 +66,15 @@ beforeEach(() => {
...
-    },
-  );
+  vi.mocked(app.getPath).mockImplementation((name: Parameters<typeof app.getPath>[0]) => {
+    if (name === 'exe') {
+      return fakeAppExe;
+    }
+    if (name === 'home') {
+      return fakeAppHome;
+    }
+    throw new Error('Unsupported path');
```
Comment (benoitf) [inline packages/main/src/system/macos-startup.spec.ts]: it is not related to the referenced changes
it should probably be a quick refactor PR targeting the replacement of the args by typeof app.getPath

issue is for Windows, this file is for macOS, etc.

File: packages/main/src/system/macos-startup.spec.ts [hunk 4]
```diff
@@ -124,35 +104,15 @@ describe('enable', () => {
...
-    );
+    vi.mocked(app.getPath).mockImplementation((name: Parameters<typeof app.getPath>[0]) => {
+      if (name === 'exe') {
+        return `/Volumes/${fakeAppExe}`;
+      }
+      if (name === 'home') {
+        return fakeAppHome;
+      }
+      throw new Error('Unsupported path');
+    });
```
Comment (benoitf) [inline packages/main/src/system/macos-startup.spec.ts]: same here, should be part of a separate refactoring PR

**Review by benoitf — COMMENTED** [review]
I'm not sure the PR description is matching what the code is doing

**Review by jeffmaury — COMMENTED** [review]
This method does not work for home folder containing spaces:

image

**Comment by dgolovin** [comment]
> This method does not work for home folder containing spaces:

@jeffmaury I have tested on Windows 10 Pro and 11 Pro.  For single and all users installations. It works as expected for me. BTW there is always space in name, because executable name is `Podman Desktop.exe`.

**Comment by jeffmaury** [comment]
> > This method does not work for home folder containing spaces:
> 
> @jeffmaury I have tested on Windows 10 Pro and 11 Pro. For single and all users installations. It works as expected for me. BTW there is always space in name, because executable name is `Podman Desktop.exe`.

Did not work for me as when I reboot I got a dialog to check executable to launch Jeff as my home folder is Jeff MAURY. And entry in the registry is invalid (missing ending quote)

**Comment by dgolovin** [comment]
@jeffmaury can you try again with this PR? I added explicit quotation.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by MarsKubeX — APPROVED** [review]
LGTM

**Review by benoitf — DISMISSED** [review]
I do not see the relationship with the changes on minimize part
