### PR TITLE
fix: registry UI layout issues

### LINKED ISSUE #148: Registry UI layout issues
### Bug description

The new registry UI has some issues with overlapping tiles and layout, especially when width is at a premium.

e.g. here the tiles overlap and X buttons are not accessible:
Screen Shot 2022-05-16 at 9 20 00 AM

Here the same problem, plus second row is indented:
Screen Shot 2022-05-16 at 9 21 19 AM

Also, no right margin.

### Operating system

MacOS 12.3.1 M1

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
This changes proposal provides polished registry UI layout.

Снимок экрана 2022-06-27 в 19 58 57
Снимок экрана 2022-06-27 в 19 59 08
Снимок экрана 2022-06-27 в 19 59 19

fixes https://github.com/containers/podman-desktop/issues/148

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte [hunk 1]
```diff
@@ -52,49 +52,54 @@ function toggleRegistryModal(): void {
...
-      <div class="w-full p-4 md:w-60 md:h-60">
-        <div
-          on:click="{() => {
-            createRegistry();
-          }}"
-          class="p-6 bg-white rounded shadow-md  hover:bg-gray-100 dark:hover:bg-gray-100 hover:cursor-pointer">
-          <div class="px-2 text-center">
-            <div class="text-3xl text-purple-800 fas fa-plus-circle" aria-hidden="true"></div>
-            <h2 class="text-xl font-bold font-bol text-purple-800">Add registry</h2>
+      <div class="pf-l-flex pf-m-column pf-m-align-self-flex-start">
```
Comment (benoitf) [inline packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: Hello, I'm wondering why you're using patternfly flex component and not the tailwind like almost everywhere ?
The Sae for alignment

File: packages/renderer/src/override.css [hunk 2]
```diff
@@ -83,3 +83,17 @@ nav .pf-c-badge.pf-m-read {
   --pf-c-modal-box__body--PaddingTop: 3.5rem;
   --pf-c-modal-box__header--body--PaddingTop: 1.5rem;
 }
+
+@media screen and (min-width: 576px) {
```
Comment (benoitf) [inline packages/renderer/src/override.css]: I think we should not touch any of these settings

Especially the important

**Review by benoitf — APPROVED** [review]
nice job

image

I'm wondering if we should display the name of the registry when hovering it (as we truncate long name) (not a -1 to merge it)

File: packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte (hunk 1 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: Updated with using Tailwindcss

**Comment by vzhukovs** [comment]
>I'm wondering if we should display the name of the registry when hovering it (as we truncate long name)

I also thought about it, I think, adding a title o hover will be a nice solution in this case. Will try to add a hover within this PR.
