### PR TITLE
fix: allow to fetch extension from OCI registries with long segments

### LINKED ISSUE #15176: unable to fetch extension OCI image with more than 2 segments
### Bug description

if Image is like my-registry.com/foo/bar/my-extension it doesn't work

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
if a registry is allowing multiple segments like my-registry/my-org/my-sub-org/my-image (rather than the classical my-registry/my-org/my-image) then it's failing to fetch properly the image in case of authentication

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/15176

### How to test this PR?

I've added a test, fix also look like straightforward to keep all the segments

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/image-registry.ts [hunk 1]
```diff
@@ -422,7 +422,8 @@ export class ImageRegistry {
       valid = true;
     } else if (slashes.length > 2 && slashes[0]) {
       registry = slashes[0];
```
Comment (simonrey1) [inline packages/main/src/plugin/image-registry.ts:424]: suggestion(non-blocking):

```ts
      registry = slashes.shift()!;
      // join all remaining parts as the image name
      name = slashes.join('/');

```

**Review by simonrey1 — APPROVED** [review]
LGTM, thanks for the new UT

File: packages/main/src/plugin/image-registry.ts (hunk 1 above)
Comment (benoitf) [reply packages/main/src/plugin/image-registry.ts:424]: using `!` is controversial, I think there is somehow a linting rule to say we should never use !

**Review by feloy — APPROVED** [review]
