### PR TITLE
fix(api): support Docker API v1.52+ event format  

### LINKED ISSUE #16273: Container status is not refreshing when starting/stopping
### Bug description

I use Podman Desktop as a frontend for docker engine. It worked a few versions earlier but at some point the container status won't update until i restart the Podman Desktop(stays green even if it has been stopped). It's installed with flatpak. Attached logs right after i stopped a container but status is not updated

[podman-desktop-20260216185002.zip](https://github.com/user-attachments/files/25347290/podman-desktop-20260216185002.zip)

### Operating system

Ubuntu 24.04 LTS

### Installation Method

Flathub (Linux)

### Version

1.25.0

### Steps to reproduce

1. Use docker engine native on linux
2. Create container using docker CLI
3. Containers will appear in Podman Desktop
4. Start/stop won't update the container's status until restarting Podman Desktop
5. If pressing stop and then stop again when the status i green will state an error that the container has already stopped.

### Relevant log output

```shell

```

### Additional context

Reproduced with:
Docker Engine 29.2.1
containerd 2.2.1

Status is refreshing when downgrading to following docker:
Docker Engine 27.5.1
containerd 1.7.29

### LINKED ISSUE #16405: ContainerJSONEvent.type (lowercase) does not exist in API response — should be Type (uppercase)
The `ContainerJSONEvent` interface defines `type: string` (lowercase, required) and `Type?: string` (uppercase, optional). This is incorrect — both the Docker and Podman APIs have always returned `Type` (uppercase) in the event JSON. Lowercase `type` has never existed in the API response.

This doesn't cause runtime issues because the codebase correctly uses `Type` (uppercase) everywhere, but the interface definition is misleading — any extension relying on `event.type` (as the interface suggests) would get `undefined`.

### Background

The Docker `Message` struct defines event fields with mixed casing in JSON:
- `status`, `id`, `from` — have explicit JSON tags (`json:"status,omitempty"` etc.), so they serialize as **lowercase**
- `Type`, `Action`, `Actor` — have **no** JSON tags, so they serialize as **uppercase** (Go default)

This has been the case since the original [docker.engine-api](https://github.com/docker-archive-public/docker.engine-api/blob/master/types/events/events.go#L29-L42), and is still the same in [Docker v28.5.2](https://github.com/moby/moby/blob/v28.5.2/api/types/events/events.go#L114-L132) (which Podman [embeds](https://github.com/containers/podman/blob/main/pkg/domain/entities/types/events.go)).

The `type: string` (lowercase) in `ContainerJSONEvent` was likely added by mistake, assuming it followed the same lowercase pattern as `status` and `id`.

### Evidence

- `type` (lowercase) is never populated and never read anywhere in the codebase
- `Type` (uppercase) is the actual field from the API stream, used 18x in `container-registry.ts` and in the `kind` extension (`event.Type === 'container'`)
- All test mocks use `Type` (uppercase)

### Suggested fix

- Remove or deprecate `type: string`
- Change `Type?: string` to `Type: string` (required)

### LINKED ISSUE #16420: Container list isn't refreshed upon deletion
### Bug description

When deleting a Docker container with Podman Desktop it will get stuck in a loading phase inside the app, whereas the container itself has been already deleted from Docker.

### Operating system

Linux Mint 22.3

### Installation Method

Flathub (Linux)

### Version

1.25.0

### Steps to reproduce

1. Create a running Docker container
2. Open Podman Desktop
3. Select your running container and press the delete button

### Relevant log output

```shell

```

### Additional context

_No response_

### LINKED ISSUE #17024: Docker 29.1.x no refresh or interaction with daemon
### Bug description

Recently, Ubuntu 24.04 LTS released an major update to docker:

```
Start-Date: 2026-04-09  15:50:22
Commandline: /usr/bin/apt install docker.io
Requested-By: XXXXXXXX
Upgrade: docker.io:amd64 (28.2.2-0ubuntu1~24.04.1, 29.1.3-0ubuntu3~24.04.1)
End-Date: 2026-04-09  15:50:36
```

This update has an impact on Podman Desktop, since the containers tap no longer tracks the changes that happen to any docker container. Stopping a container does still work... but the UI is never refreshed.

### Operating system

Linux Mint (22.1), Ubuntu 24.04 LTS

### Installation Method

Flathub (Linux)

### Version

1.26.0

### Steps to reproduce

# Scenario 1 
- Install the latest Docker.io package and Podman Desktop on Ubuntu 24.04 LTS
- Start a docker container from the command line
- Open Podman Desktop
- See that the container exists
- Stop the container
- ... No UI feedback
- Validate that the container stopped using the terminal

# Scenario 2
- Install the latest Docker.io package and Podman Desktop on Ubuntu 24.04 LTS
- Start Podman Desktop and go to the containers tab
- Start a docker container from the command line
- ... No UI feedback
- Validate that the container is properly running in the background

### Relevant log output

```shell

```

### Additional context

_No response_

### LINKED ISSUE #17229: Support Docker 29.1.x
### Epic domain

In the new major release of Docker 29.1, Podman Desktop UI is not refreshed or updated based on the CLI actions.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

Docker Engine 29 (API v1.52+) removed the deprecated top-level `status`, `id` and `from` fields from the `/events` stream, replacing them with `Action` and `Actor.ID`. This broke automatic UI updates — containers, images, volumes and networks stopped refreshing in the dashboard for Docker 29+ users.

This PR adds optional `Action` and `Actor` fields to the internal `JSONEvent` interface, then falls back to these new fields when the old ones are absent. Events are normalized before being emitted to extensions — `status` and `id` are always populated from `Action`/`Actor.ID` when missing — so **no changes are needed to the public `ContainerJSONEvent` extension API**. Docker compound actions like `health_status: healthy` are split to extract the base action.

Both types are kept separate intentionally — [per project convention](https://github.com/podman-desktop/podman-desktop/pull/16403#pullrequestreview-3902774774) the internal type can diverge from the one published to extensions.

Supersedes #16388 (author unresponsive).

### What issues does this PR fix or reference?

Fixes #17229
Fixes #17024
Fixes #16405
Fixes #16420
Fixes #16273

### How to test this PR?

1. Install Docker Desktop 4.44+ (Docker Engine 29, API v1.52+)
2. `pnpm watch` from this branch
3. **Test 1 — CLI events reflected in UI:**
   ```bash
   docker run -d --name test-event nginx
   docker stop test-event
   docker start test-event
   docker rm -f test-event
   ```
   Confirm the Containers tab updates in real time for each action.

4. **Test 2 — UI controls work:**
   - `docker run -d --name test-ui nginx`
   - In Podman Desktop, click the stop button on the container
   - Confirm the container shows as stopped
   - Click the start button
   - Confirm the container shows as running again
   - Delete the container from the UI

5. Run unit tests: `pnpm exec vitest run packages/main/src/plugin/container-registry.spec.ts` — 178 tests pass (174 existing + 4 new)

- [x] Tests are covering the bug fix or the new feature

> [!NOTE]
> This PR was authored with AI assistance.

### CODE REVIEW

File: packages/extension-api/src/extension-api.d.ts [hunk 1]
```diff
@@ -3149,6 +3149,10 @@ declare module '@podman-desktop/api' {
     status: string;
     id: string;
     Type?: string;
+    Action?: string;
+    Actor?: {
+      ID: string;
+    };
```
Comment (benoitf) [inline packages/extension-api/src/extension-api.d.ts]: question: do we need to expose the details of the Docker event ?

I mean, extensions are not expected to be updated so I guess it should not spread/distribute over the extension api

Comment (simonrey1) [reply packages/extension-api/src/extension-api.d.ts]: Good call, I had the same thought but initially kept both types in sync for consistency. Agreed it's better to not leak Docker internals into the extension API. Will update to normalize the event before firing so extensions always see `status`/`id` populated, and keep `Action`/`Actor` only on the internal `JSONEvent`.

**Review by benoitf — DISMISSED** [review]
LGTM

**Comment by simonrey1** [comment]
Adding @podman-desktop/qe-reviewers because this needs some advanced testing with Docker and Podman engines

File: packages/main/src/plugin/container-registry.ts [hunk 2]
```diff
@@ -190,8 +192,10 @@ export class ContainerProviderRegistry {
       // reconnected
       this.notify = true;
 
-      const status = jsonEvent.status;
-      const id = jsonEvent.id;
+      // Podman uses top-level `status`/`id`; Docker API v1.52+ uses `Action`/`Actor.ID` instead.
+      // Docker can emit compound Action values like "health_status: healthy" — keep only the base action.
+      const status = jsonEvent.status ?? jsonEvent.Action?.split(':')[0]?.trim();
+      const id = jsonEvent.id ?? jsonEvent.Actor?.ID;
```
[the remark this answers is not in the document]
Comment (simonrey1) [reply packages/main/src/plugin/container-registry.ts:198]: Good, I was unsure if we should override it, I will take a look before we continue

**Comment by simonrey1** [comment]
Updated the code to handle normalization of the event (updated PR description too)

**Review by benoitf — APPROVED** [review]
the container was properly updated in the UI if started or stopped it

**Review by vancura — APPROVED** [review]

**Review by axel7083 — APPROVED** [review]

**Comment by danivilla9** [comment]
Just tested on Windows 10, everything works as expected

**Comment by SoniaSandler** [comment]
@Mergify backport 1.27.x
