### PR TITLE
fix: pass options when listing images with Docker API fallback

### LINKED ISSUE #16422: Docker API fallback ignores options in podmanListImages
### Bug description

When `podmanListImages` falls back to the Docker API (line 669), it hardcodes `{ all: false }` instead of passing through the caller's options (`options?.all`, `options?.filters`).

#### Expected behavior
Docker API fallback should pass through the same options as libpod API path.

### Operating system

Omarchy 3.4.1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Call `podmanListImages({ all: true })` on a provider using Docker API fallback
2. Intermediate images are not included, unlike with libpod API providers

### Relevant log output

```shell

```

### Additional context

Spotted by CodeRabbit in PR #16404

### PR DESCRIPTION
**Pull request by sheikhlimon**
### What does this PR do?
When listing images with options like `{ all: true }`, the Docker API fallback was ignoring these options and hardcoding `{ all: false }`. This meant intermediate images were hidden unexpectedly. Now options are properly passed through, so image listing works consistently across all providers.

### What issues does this PR fix or reference?

Fixes #16422 

### How to test this PR?

unit test

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/container-registry.ts [hunk 1]
```diff
@@ -666,7 +665,10 @@ export class ContainerProviderRegistry {
             filters: options?.filters,
           });
         } else if (provider.api) {
-          fetchedImages = await provider.api.listImages({ all: false });
+          fetchedImages = await provider.api.listImages({
```
Comment (simonrey1) [inline packages/main/src/plugin/container-registry.ts]: question: it it posible to apply DRY here? For example, this parameter used both in both if / else if blocks could be introduced before the if block? 
I see a minor difference with `options?.all ?? false` though, so I am not sure?

Comment (sheikhlimon) [reply packages/main/src/plugin/container-registry.ts]: Good catch! my understanding is that `undefined` and `false` behave the same since Podman defaults to `false`, so I applied DRY by creating `listOptions` once for both paths (see 935f5f3).

**Review by simonrey1 — APPROVED** [review]
LGTM, not tested with Docker

**Comment by simonrey1** [comment]
@sheikhlimon I think there is a merge issue in this PR. Could you please take a look (lot of files modified).

**Review by simonrey1 — APPROVED** [review]
LGTM (see comments above)

**Comment by sheikhlimon** [comment]
> @sheikhlimon I think there is a merge issue in this PR. Could you please take a look (lot of files modified).

Sorry, I merged main instead of rebasing while fixing conflicts, which pulled in all those extra files.

**Review by benoitf — APPROVED** [review]
