### PR TITLE
fix(renderer/help-menu): provide names of font awesome icons

### LINKED ISSUE #15512: [help-menu]: Replace imported font awesome icons with their names
### Task content

In the current help menu, the icons are imported but in the productized version, we need to declare the icons in the JSON file, so we should change to provide the icon name (serializable) instead of the import.

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

This PR provides the explicit names of the font awesome icons used in the help menu instead of importing them. This is helpful for the epic of the productization of the help menu : the icons will be declared in the `product.json` file.

Needs a rebase after:

- https://github.com/podman-desktop/podman-desktop/pull/15511 is merged
- https://github.com/podman-desktop/podman-desktop/pull/15518 is merged

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/15512

### How to test this PR?

Check that there is no change in the help menu icons

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/help/HelpItems.ts [hunk 1]
```diff
@@ -16,16 +16,6 @@
...
-import { faComment } from '@fortawesome/free-regular-svg-icons';
-import {
-  faExclamationTriangle,
-  faExternalLinkAlt,
-  faLightbulb,
-  faListUl,
-  type IconDefinition,
-} from '@fortawesome/free-solid-svg-icons';
-
 import { homepage, repository } from '../../../../../package.json';
```
Comment (axel7083) [inline packages/renderer/src/lib/help/HelpItems.ts:19]: I find it interesting that we are doing a major refactor because we don't want to import the `product.json` but we are already importing the `package.json`

**Review by axel7083 — APPROVED** [review]
LGTM

File: packages/renderer/src/lib/help/HelpItems.ts (hunk 1 above)
Comment (simonrey1) [reply packages/renderer/src/lib/help/HelpItems.ts:19]: I tried to import it in this PR but it was blocked: https://github.com/podman-desktop/podman-desktop/pull/15380

**Comment by simonrey1** [comment]
Screenshot 2025-12-29 at 17 48 21

Before we merge this I am worried that this introduces a misalignment but I need to investigate why


Edit: fixed
