### PR TITLE
fix(Roseta): fixed Roseta enablement on macOS Tahoe with Podman 5.6+

### LINKED ISSUE #16168: enabling rosetta in the UI should enable it in the VM, but it doesn't
### Bug description

Earlier today, I was trying to run an amd64 container image on my arm64 MacBook, and I was getting a segfault, which suggests that it's using qemu and not rosetta.  I updated to the latest Podman and Podman Desktop versions, made sure rosetta was enabled in the UI, and recreated my VM, making sure to use the Apple HyperVisor and not libkrun. 

Image

Image

Running `podman machine inspect` gives the expected output, `"Rosetta": true`.

```
% podman machine inspect
[
     {
          "ConfigDir": {
               "Path": "/Users/user/.config/containers/podman/machine/applehv"
          },
          "ConnectionInfo": {
               "PodmanSocket": {
                    "Path": "/var/folders/r4/q1fqknzx7_zbb05205s93bnc0000gp/T/podman/podman-machine-default-api.sock"
               },
               "PodmanPipe": null
          },
          "Created": "2026-02-10T17:27:35.291496-06:00",
          "LastUp": "0001-01-01T00:00:00Z",
          "Name": "podman-machine-default",
          "Resources": {
               "CPUs": 6,
               "DiskSize": 93,
               "Memory": 3814,
               "USBs": []
          },
          "SSHConfig": {
               "IdentityPath": "/Users/user/.local/share/containers/podman/machine/machine",
               "Port": 53814,
               "RemoteUsername": "core"
          },
          "State": "running",
          "UserModeNetworking": true,
          "Rootful": true,
          "Rosetta": true
     }
]
```

But even with all this, still segfault, which suggests that rosetta is still not enabled.  It turns out that you need to go to https://blog.podman.io/2025/08/podman-5-6-released-rosetta-status-update/ and follow these manual instructions to actually enable rosetta for real.  

Using those instructions, I'm able to confirm that rosetta is not actually enabled in the VM

```
% podman machine ssh "cat /proc/sys/fs/binfmt_misc/rosetta"
cat: /proc/sys/fs/binfmt_misc/rosetta: No such file or directory
```

But following the instructions from the blog post got it enabled, and my segfaults are gone now.

```
% podman machine ssh "sudo touch /etc/containers/enable-rosetta"
% podman machine stop ; podman machine start
Machine "podman-machine-default" stopped successfully
Starting machine "podman-machine-default"
API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
% podman machine ssh "cat /proc/sys/fs/binfmt_misc/rosetta"
enabled
interpreter /mnt/rosetta
flags: POCF
offset 0
magic 7f454c4602010100000000000000000002003e00
mask fffffffffffefe00fffffffffffffffffeffffff
```

Rosetta should have been enabled when I created and started the VM, but it wasn't.  Additionally, `podman machine inspect` gave misleading results.  

### Operating system

macOS Tahoe 26.2 (arm64)

### Installation Method

Installer from website/GitHub releases

### Version

1.25.0

### Steps to reproduce

- Install the latest Podman (5.7.1) and Podman Desktop (1.25.1) on an arm64 macOS host running macOS Tahoe.  
- Ensure that Rosetta is enabled in the Podman Desktop preferences.
- Create a new Podman VM, taking care to choose the Apple HyperVisor and not libkrun
- Ensure the VM is started
- run `podman machine ssh "cat /proc/sys/fs/binfmt_misc/rosetta"` and observe that Rosetta is not enabled even though it should be

### Relevant log output

When rosetta is disabled:

```shell
% podman run mcr.microsoft.com/mssql/server
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
SQL Server 2025 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
/opt/mssql/bin/launch_sqlservr.sh: line 37:     9 Segmentation fault      (core dumped) "$@"
```

When rosetta is enabled (don't worry about the failed assertion):

```shell
% podman run mcr.microsoft.com/mssql/server
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
SQL Server 2025 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
assertion failed [x86_avx_state_ptr->xsave_header.xfeatures == kSupportedXFeatureBits]:
(ThreadContextSignals.cpp:414 rt_sigreturn)
 ^C
```

### Additional context

See also: https://github.com/containers/podman/issues/27554

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
This PR adds a fix from https://blog.podman.io/2025/08/podman-5-6-released-rosetta-status-update/ to creation/starting of podman machine on macOS Tahoe with podman 5.6+

### What issues does this PR fix or reference?
Closes https://github.com/podman-desktop/podman-desktop/issues/16168

### How to test this PR?
Create podman machine from podman desktop (production version) - applev provider
Start the machine, run `podman machine ssh "cat /proc/sys/fs/binfmt_misc/rosetta"` (for podman-machine-default) - you should see `cat: /proc/sys/fs/binfmt_misc/rosetta: No such file or directory`

Run PD from this PR, try to stop/start the machine 
run `podman machine ssh "cat /proc/sys/fs/binfmt_misc/rosetta"` 
You should see: ±
```
enabled
interpreter /mnt/rosetta
flags: POCF
offset 0
magic 7f454c4602010100000000000000000002003e00
mask fffffffffffefe00fffffffffffffffffeffffff
```

Delete the machine, create new machine (also with appleV)
run the command again, you should see the same output

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by benoitf — CHANGES_REQUESTED** [review]
we've enabled inversify in this extension so we should not bring any exported function but only bring injection of objects / classes

File: extensions/podman/packages/extension/src/extension.ts [hunk 1]
```diff
@@ -2134,7 +2153,9 @@ export async function createMachine(
   }
 
   // name at the end
+  let machineName = 'podman-machine-default';
```
Comment (benoitf) [inline extensions/podman/packages/extension/src/extension.ts]: I don't see why we need to get the default machine name

the command 'podman machine ssh' works without provide the default name of the machine

if podman cli decides to rename the default machine name from 'podman-machine-default' to 'default' we're screwed here

I think it should provide the name of the machine later only if it's defined, else it should assume the default naming

Comment (gastoner) [reply extensions/podman/packages/extension/src/extension.ts]: Removed the default name

Comment (gastoner) [reply extensions/podman/packages/extension/src/extension.ts]: Forgot to push it :D

Comment (benoitf) [reply extensions/podman/packages/extension/src/extension.ts]: @gastoner I think it should not be empty machine name but when you call the 'podman machine ssh' the element should not be there

like you prepare the argument, if there is a custom machine name, you add the machine name to the array else you keep the arguments

**Review by amisskii — APPROVED** [review]
LGTM. Functionality tested only

**Review by benoitf — APPROVED** [review]

**Comment by gastoner** [comment]
Rebasing based on latest main
