### PR TITLE
fix(plugin): address admzip filename issue on macos

### LINKED ISSUE #15286: Error while loadPackagedFile Error: ADM-ZIP: Invalid filename on fresh start on Mac OS
### Bug description

I got following error while starting nightly PD on mac OS: `Error while loadPackagedFile Error: ADM-ZIP: Invalid filename`

It does not appear if I start second time.

### Operating system

Mac OS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Clean pd home folder: `rm -rf ~/.local/share/containers/podman-desktop`
2. Start up podman nightly (1.25.0-next - main branch)

### Relevant log output

```shell
VM5:2 main ↪️ [kind] kind extension is active
VM5:2 main ↪️ Activating extension (podman-desktop.podman) ended in 52 milliseconds
VM5:2 main ↪️ Activating extension (podman-desktop.podman-docker-context) with max activation time of 20 seconds
VM5:2 main ↪️ Activating extension (podman-desktop.podman-docker-context) ended in 0 milliseconds
VM5:2 main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
VM5:2 main ↪️ Activating extension (podman-desktop.registries) ended in 0 milliseconds
VM5:2 main ↪️ PluginSystem: initialization done.
VM5:2 main ↪️ Autostarting podman-desktop.podman container engine
VM5:2 main ↪️ [kind] kind extension is active
VM5:2 main ↪️ [kind] kind extension is active
VM5:2 main ↪️ Error while loadPackagedFile Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:6:3964)
    at new admZip (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:6:29924)
    at ExtensionLoader.loadPackagedFile (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:222:23224)
    at Timeout._onTimeout (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:222:25479)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
console.<computed> @ VM5:2
welcome-utils.ts:42 Telemetry enablement: false
```

### Additional context

Stumbled upon this while testing https://github.com/podman-desktop/podman-desktop/pull/15277

### PR DESCRIPTION
**Pull request by bmahabirbu**
when a new directory is created fs.watcher emits an unintended error. We should filter only by .cdix extension files to avoid this

### What issues does this PR fix or reference?

Fixes: https://github.com/podman-desktop/podman-desktop/issues/15286

### How to test this PR?
 on macos 
 remove the config files
 ```rm -rf ~/.local/share/containers/podman-desktop```
 run with pnpm watch and look for the logs discussed in the issue
 i noticed it was flaky so try a couple of times

- [ ] Tests are covering the bug fix or the new feature

Looking for feedback for creating a test. So far I think this is mac specific

### CODE REVIEW

File: packages/main/src/plugin/extension/extension-loader.ts [hunk 1]
```diff
@@ -425,8 +425,9 @@ export class ExtensionLoader implements IAsyncDisposable {
     if (fs.existsSync(this.pluginsScanDirectory)) {
       // add watcher
       fs.watch(this.pluginsScanDirectory, (_, filename) => {
-        // need to load the file
-        if (filename) {
+        // Only process .cdix extension files
+        // Note: macOS fs.watch can emit an unintended error when watching a newly created directory
+        if (filename?.endsWith('.cdix')) {
```
Comment (simonrey1) [inline packages/main/src/plugin/extension/extension-loader.ts:430]: question: do you enter this if when debugging (or logging)? I try to understand how this is used.

Comment (simonrey1) [reply packages/main/src/plugin/extension/extension-loader.ts:430]: My point is that if the "plugins-scanning" directory is not used anymore, we should rather remove it.

Comment (bmahabirbu) [reply packages/main/src/plugin/extension/extension-loader.ts:430]: I believe it's used when scanning the .local/share/containers/podman-desktop directory for the various configuration files but will investigate further on how the whole scanning plugin system works

**Review by jeffmaury — APPROVED** [review]
LGTM but wondering why this error has been emitted

**Comment by simonrey1** [comment]
Before merging, I was wondering is this "plugins-scanning" directory still in use?
I did not find any mention of it the documentation, or in tests.
So, in my opinion, another fix for this issue would be to remove this directory and the associated file watcher.


@benoitf @podman-desktop/qe-reviewers

**Comment by benoitf** [comment]
I would only add a notice that usually a feature can't be removed without deprecation first, so we could not remove as part of the issue fix

**Comment by bmahabirbu** [comment]
Thanks all for the checks! To me, since this is a small change, we can get this in and add a ticket to explore/remove the plugin-scanning feature

**Comment by bmahabirbu** [comment]
@jeffmaury what ive found is that the error occurs on the first run of pd when the directory is being created. The watcher will fire an erroneous message that is mac specific

**Comment by bmahabirbu** [comment]
@simonrey1 

From what I found is that the plugins-scanning directory is a drop in installation mechanism. Drop a .cdix file (which is a zip format of an extension) into ~/.local/share/podman-desktop/plugins-scanning pd will automatically detects it via a file watcher The file is extracted to an unpacked/ directory. Its use is in extension-loader.ts Lines 310-320

This feature is still useful for testing nightly builds of extensions in ci imo. Ai lab uses it but maybe other ci uses it?

**Review by simonrey1 — APPROVED** [review]
