### PR TITLE
fix(plugin): improves port validation and error handling in getFreePort method

### LINKED ISSUE #14353: create kind cluster with wrong port number will crash the podman
### Bug description

Image
when we create kind cluster, if we input the http port with out of range number, then podman will hang there and not responed.

### Operating system

macos tahoe 26.0.1

### Installation Method

Installer from website/GitHub releases

### Version

1.22.0

### Steps to reproduce

**PodMan** --> **Settings** --> **Resources** --> **Kind** --> **Create new...** --> **Http Port** --> Input **99901**
then podman will hang there

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?

The following PR improves port validation and error handling in the `getFreePort()` method and Kind extension:

1. **Prevents infinite loop in `getFreePort()`** - Added validation to reject invalid port numbers (> 65535 or NaN) at the entry point, preventing the application from hanging when invalid ports are provided
2. **Adds upper boundary check in port iteration** - Ensures the port search loop terminates when reaching the valid port range limit (65535)
3. **Refactors duplicated code in Kind extension** - Extracted `validateAndCheckPort()` function to eliminate code duplication and improve maintainability
4. **Improves error messages for better UX** - Provided additional error messages if user tries to enter port number that is out of valid range.

### Screenshot / video of UI

- When user tries to enter both ports that needs a root permissions and both are equal:

- When user tries to enter a single port that requires a root permissions, another one is valid:

- When user enters both ports that are equal, but valid:

- When user tries to enter port number that is out of valid range:

- When user tries to enter port number that is out of valid range, another one is required a root permissions:

- When user tries to enter both valid ports and are not equal:

### What issues does this PR fix or reference?

fixes #14353 

### How to test this PR?

1. Navigate to the **Kind Create** connection page through **Settings** -> **Resources** -> **Kind** -> **Create new ...**
2. Try to enter various integer values to the HTTP and HTTPS ports.
3. Podman Desktop should display an error message in case if port number is out of a valid range, e.g. > 65535 instead of freezing and crushing.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/util/port.ts [hunk 1]
```diff
@@ -21,13 +21,26 @@ import { type NetworkInterfaceInfoIPv4, networkInterfaces } from 'node:os';
...
+
   if (port < 1024) {
     port = 9000;
   }
+
   let isFree = false;
   while (!isFree) {
+    // Check if we've exceeded the valid port range during iteration
+    if (port > 65535) {
+      throw new Error('Unable to find a free port: all ports in the valid range (1024-65535) are busy.');
```
Comment (simonrey1) [inline packages/main/src/plugin/util/port.ts:41]: nitpick: the range indicated is incorrect

the ports are only checked between `port` parameter and 65535

Comment (vzhukovs) [reply packages/main/src/plugin/util/port.ts:41]: this is the original logic, which is not changed, the only upper range is limited

or you mean, that we should update message of provided Error to indicate that `valid range (${port}-65535) are busy.`, am I right?

Comment (simonrey1) [inline packages/main/src/plugin/util/port.ts:41]: in case of error ('Please enter a port number between 0 and 65535.' and 'Unable to find a free port: all ports in the valid range (1024-65535) are busy.'), the interface remains stucked.

Image

I changed 

`const freePort = await window.getFreePort(100_000);`

in 
`packages/renderer/src/lib/kube/details/KubePort.svelte`

to simulate this error

**Review by simonrey1 — APPROVED** [review]
LGTM, tested on Mac

The errors are correctly displayed and dismissed automatically.

Image

Image

**Review by MarsKubeX — APPROVED** [review]
LGTM. Tested and working fine in MacOS
