### PR TITLE
fix: show default app version in statusbar for any auto updater error

### LINKED ISSUE #15990: Podman Desktop status bar version is missing if app-update file is missing
### Bug description

The Version in the status bar is missing if app-update.yml is missing from the installation. I think we should show version even though we lack the electron updater configuration file. 

### Operating system

any

### Installation Method

None

### Version

1.25.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
Co-Authored-By: Charlie Drage <charlie@charliedrage.com>

### What does this PR do?
This PR adds a fix so that any error coming from autoUpdater will use the default app version instead of only for GitHub errors

### What issues does this PR fix or reference?
Fixes https://github.com/podman-desktop/podman-desktop/issues/15990

### How to test this PR?

macOS:

1. `pnpm compile:current`
2. `codesign --force --deep --sign - "dist/mac-arm64/Podman Desktop.app"`
3. `rm "dist/mac-arm64/Podman Desktop.app/Contents/Resources/app-update.yml"`
4. Start Podman Desktop
5. See that the version now appears in the status bar.

Windows:

1. `pnpm compile:current`
2. Delete `dist\win-unpacked\resources\app-update.yml`
3. Start Podman Desktop
4. See that the version now appears in the status bar on the bottom
   right

**NOTE!!** You can also test this out against the `main` branch as well,
and see that if we edit / remove the `app-update.yml` from within the
app (in the case of macOS within the `Podman Desktop.app`, you can see
that the current bug exists across both mac and windows

- [X] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
LGTM Codewise

**Review by axel7083 — APPROVED** [review]
LGTM codewise

File: packages/main/src/plugin/updater.ts [hunk 1]
```diff
@@ -427,9 +427,10 @@ export class Updater {
     // local build not pushed to GitHub so prevent any 'update'
     if (error?.message?.includes('No published versions on GitHub')) {
       console.log('Cannot check for updates, no published versions on GitHub');
-      this.defaultVersionEntry();
-      return;
+    } else {
+      console.error('unable to check for updates', error);
```
Comment (benoitf) [inline packages/main/src/plugin/updater.ts]: I'm not sure to understand as well why we have the else block being added ?
we'll see the error line 434

**Review by benoitf — APPROVED** [review]

**Comment by danivilla9** [comment]
Just checked on Windows, everything seems to work as expected

**Review by amisskii — APPROVED** [review]
Tested on mac. LGTM

**Review by serbangeorge-m — APPROVED** [review]
